"""The cardinal corpus, written as data.

Levels 1-5 carry NO directional language: the description identifies the two
places and stops, so the answer has to come from knowing where they are.
Difficulty is therefore a property of the pair, not of the wording -- Level 1
pairs match everyone's mental map, Level 5 pairs contradict it.

Level 6 is the exception. It states two links through an intermediate place and
the reader composes them, so directional phrasing is required there.

Every pair is checked by build_cardinal_corpus.py against real coordinates.
"""



# (level, label, source, target, via, description)
ROWS = [
    # ---------------- north_of ----------------
    (1, "north_of", "Oslo", "Rome", None,
     "Oslo grew up at the head of a long fjord and holds Norway's seat of government. Rome, the Italian capital, is built around a bend of the Tiber."),
    (1, "north_of", "Helsinki", "Athens", None,
     'Helsinki faces the Gulf of Finland across a granite shoreline. Athens has been continuously inhabited for more than three thousand years.'),
    (1, "north_of", "New York", "Bogota", None,
     'New York anchors the largest metropolitan economy in the United States. Bogota is the Colombian capital, spread across a high Andean basin.'),
    (2, "north_of", "London", "Accra", None,
     "London developed along a tidal stretch of the Thames. Accra serves as Ghana's capital and its busiest port."),
    (2, "north_of", "Berlin", "Luanda", None,
     'Berlin spent four decades split between two political blocs. Luanda, the Angolan capital, ranks among the most expensive cities on the continent for expatriate workers.'),
    (2, "north_of", "Miami", "Lima", None,
     "Miami handles a large share of the air traffic between the United States and the Caribbean. Lima was founded by Pizarro in 1535 and remains Peru's capital."),
    (3, "north_of", "Warsaw", "Cape Town", None,
     "Warsaw was reconstructed almost entirely after 1945, much of it from painted records. Beneath Table Mountain, Cape Town houses South Africa's parliament."),
    (3, "north_of", "Amsterdam", "Lagos", None,
     'Amsterdam is built on wooden piles driven into soft ground and threaded with canals. Lagos has become the most populous city in Africa.'),
    (3, "north_of", "Quito", "Santiago", None,
     "Quito stands at roughly 2,850 metres and is Ecuador's capital. Santiago is hemmed between the Andes and Chile's coastal range."),
    (4, "north_of", "Bratislava", "Windhoek", None,
     "Bratislava sits on the Danube within sight of two international borders. Windhoek is Namibia's capital, set on a dry inland plateau."),
    (4, "north_of", "Gothenburg", "Maputo", None,
     "Gothenburg is Sweden's second city and the site of its largest port. Maputo serves Mozambique as both capital and deepwater harbour."),
    (4, "north_of", "Sarajevo", "Harare", None,
     'Sarajevo lies in a narrow valley in Bosnia and Herzegovina. Harare is the Zimbabwean capital, built on the Mashonaland plateau.'),
    (5, "north_of", "Washington", "Lima", None,
     'Washington was laid out on land ceded by Maryland and Virginia. Lima has grown into one of the largest cities on the Pacific rim of the Americas.'),
    (5, "north_of", "Ashgabat", "Muscat", None,
     "Ashgabat, the Turkmen capital, was rebuilt after the earthquake of 1948. Muscat is Oman's capital, wedged between the Hajar mountains and the sea."),
    (5, "north_of", "Malmo", "Windhoek", None,
     'Malmo is joined to Copenhagen by the Oresund bridge and tunnel. Namibia governs itself from Windhoek, a city of about half a million.'),
    # ---------------- south_of ----------------
    (1, "south_of", "Cape Town", "Cairo", None,
     'Cape Town is the legislative capital of South Africa. Cairo is the largest city in the Arab world and sits astride the Nile.'),
    (1, "south_of", "Lagos", "London", None,
     'Lagos has become the most populous city in Africa. London developed along a tidal stretch of the Thames.'),
    (1, "south_of", "Johannesburg", "Helsinki", None,
     'Johannesburg grew out of the gold rush of the 1880s. Helsinki faces the Gulf of Finland across a granite shoreline.'),
    (2, "south_of", "Harare", "Khartoum", None,
     'Harare was known as Salisbury until 1982. Khartoum stands where the Blue and White Niles meet.'),
    (2, "south_of", "Antananarivo", "Mogadishu", None,
     "Antananarivo is the Malagasy capital, built across a ridge of hills. Mogadishu is Somalia's capital and its principal Indian Ocean port."),
    (2, "south_of", "Luanda", "Tunis", None,
     'Luanda ranks among the costliest cities on its continent for expatriate workers. Tunisia is governed from Tunis, on the gulf of the same name.'),
    (3, "south_of", "Windhoek", "Kinshasa", None,
     "Windhoek's architecture still shows its German colonial period. Kinshasa faces Brazzaville across the Congo river."),
    (3, "south_of", "Valparaiso", "La Paz", None,
     "Valparaiso is Chile's chief seaport and the seat of its national congress. La Paz is the highest seat of government anywhere."),
    (3, "south_of", "Santiago", "Caracas", None,
     "Santiago holds roughly forty percent of Chile's population. Caracas lies in a narrow valley cut off from the Caribbean by a coastal range."),
    (4, "south_of", "Maputo", "Riga", None,
     "Maputo is Mozambique's capital and its deepwater port. Riga's old town is a dense collection of medieval and art nouveau buildings."),
    (4, "south_of", "Windhoek", "Bergen", None,
     "Windhoek's architecture still carries traces of its German colonial period. Bergen receives some of the heaviest rainfall in Europe."),
    (4, "south_of", "Quito", "Toronto", None,
     'Quito was among the first places inscribed as a world heritage site. Toronto is the most populous city in Canada.'),
    (5, "south_of", "Maputo", "Tallinn", None,
     "Maputo was called Lourenco Marques until 1976. Tallinn's walled centre is among the best preserved in the Baltic."),
    (5, "south_of", "Accra", "Paris", None,
     "Accra became the seat of colonial administration in 1877 and remains Ghana's capital. Paris draws more visitors than any other European city."),
    (5, "south_of", "Khartoum", "Helsinki", None,
     'Khartoum stands where the Blue and White Niles converge. Finland runs its government from Helsinki, a city of some 650,000 people.'),
    # ---------------- east_of ----------------
    (1, "east_of", "Delhi", "Baghdad", None,
     'Delhi has served as a seat of empire many times over. Baghdad was founded in 762 as a round city on the Tigris.'),
    (1, "east_of", "Islamabad", "Tehran", None,
     "Islamabad was purpose-built in the 1960s to replace Karachi as Pakistan's capital. Tehran sprawls at the foot of the Alborz range."),
    (1, "east_of", "Ankara", "Marseille", None,
     "Ankara replaced Istanbul as Turkey's capital in 1923. Marseille has been a working port since Greek traders founded it."),
    (2, "east_of", "Colombo", "Addis Ababa", None,
     "Colombo is Sri Lanka's commercial capital and largest port. Addis Ababa lies at around 2,350 metres in the Ethiopian highlands."),
    (2, "east_of", "Yangon", "Riyadh", None,
     "Yangon was Myanmar's capital until 2006 and holds the Shwedagon Pagoda. Riyadh grew from a walled desert settlement into a city of millions."),
    (2, "east_of", "Amman", "Algiers", None,
     "Amman is built over a set of hills once called Philadelphia. Algiers is Algeria's capital and its largest port."),
    (3, "east_of", "Karachi", "Cairo", None,
     "Karachi is Pakistan's financial centre and its window on the Arabian Sea. Cairo governs Egypt from the head of the Nile delta."),
    (3, "east_of", "Beirut", "Tunis", None,
     'Beirut occupies a headland projecting into the Mediterranean. Tunis administers Tunisia and its Mediterranean coastline.'),
    (3, "east_of", "Vientiane", "Dubai", None,
     'Vientiane is the Lao capital and sits on the Mekong. Dubai built a global transport hub on what was a pearling and trading coast.'),
    (4, "east_of", "Singapore", "Mogadishu", None,
     "Singapore is a city-state that separated from Malaysia in 1965. Mogadishu has one of the longest coastlines of any African capital's country."),
    (4, "east_of", "Lagos", "San Juan", None,
     "Lagos was Nigeria's capital until Abuja took the role in 1991. San Juan is the capital of Puerto Rico and among the oldest European-founded cities in the Americas."),
    (4, "east_of", "Damascus", "Valencia", None,
     "Damascus claims one of the longest records of continuous settlement anywhere. Valencia is Spain's third city and the home of paella."),
    (5, "east_of", "Nairobi", "Fortaleza", None,
     "Nairobi is Kenya's capital and the largest city between Cairo and Johannesburg. Fortaleza is a Brazilian state capital of some two and a half million people."),
    (5, "east_of", "Suva", "Pune", None,
     "Suva is the Fijian capital, on the island of Viti Levu. Pune was the seat of the Maratha empire and now builds much of India's vehicle fleet."),
    (5, "east_of", "Kampala", "Kingston", None,
     "Kampala replaced Entebbe as Uganda's capital at independence. Kingston is Jamaica's capital and holds a large natural harbour."),
    # ---------------- west_of ----------------
    (1, "west_of", "Casablanca", "Athens", None,
     "Casablanca handles most of Morocco's seaborne trade. Athens is the Greek capital, dominated by the Acropolis."),
    (1, "west_of", "Accra", "Mumbai", None,
     "Accra sits on the Gulf of Guinea. Mumbai is India's financial capital and home to its film industry."),
    (1, "west_of", "Nicosia", "Ashgabat", None,
     'Nicosia is the last divided capital in Europe. Ashgabat is known for its white marble public buildings.'),
    (2, "west_of", "Kampala", "Manila", None,
     "Kampala is Uganda's capital, built across a set of low hills near Lake Victoria. Manila anchors a metropolitan region of over thirteen million."),
    (2, "west_of", "Addis Ababa", "Yangon", None,
     "Ethiopia governs itself from Addis Ababa, a city founded in 1886. Yangon remains Myanmar's largest city and commercial centre."),
    (2, "west_of", "Abu Dhabi", "Kathmandu", None,
     'Abu Dhabi is the capital of the United Arab Emirates and holds most of its oil reserves. Kathmandu lies in a bowl-shaped valley in Nepal.'),
    (3, "west_of", "Lagos", "Pune", None,
     'Lagos is built around a lagoon and a set of islands. Pune is a major Indian centre for education and vehicle manufacturing.'),
    (3, "west_of", "Salvador", "Windhoek", None,
     'Salvador is the capital of Bahia and a centre of Afro-Brazilian culture. Windhoek serves a country with the second-lowest population density on earth.'),
    (3, "west_of", "Jakarta", "Suva", None,
     "Jakarta is Indonesia's capital and is subsiding fast enough that a replacement is being built. Suva is the Fijian capital, on the island of Viti Levu."),
    (4, "west_of", "Mogadishu", "Kuala Lumpur", None,
     "Mogadishu was a major medieval trading port. Kuala Lumpur grew from a tin-mining settlement into Malaysia's capital."),
    (4, "west_of", "Bogota", "Harare", None,
     "Bogota is one of the highest capital cities in the world. Harare is Zimbabwe's largest city and its administrative centre."),
    (4, "west_of", "Managua", "Windhoek", None,
     "Managua sits beside a lake of the same name and has been rebuilt after two major earthquakes. Namibia's government sits in Windhoek."),
    (5, "west_of", "Kampala", "Singapore", None,
     "Kampala replaced Entebbe as Uganda's capital at independence. Singapore handles one of the busiest container ports anywhere."),
    (5, "west_of", "Guayaquil", "Harare", None,
     "Guayaquil is Ecuador's largest city and its principal port. Harare stands at about 1,500 metres, which keeps its climate temperate."),
    (5, "west_of", "Accra", "Pune", None,
     "Accra became Ghana's capital in 1877. Pune was the seat of the Maratha empire."),
    # ---------------- northeast_of ----------------
    (1, "northeast_of", "Tokyo", "Ho Chi Minh City", None,
     "Tokyo has been Japan's administrative centre since the Tokugawa era. Ho Chi Minh City was known as Saigon and remains Vietnam's commercial hub."),
    (1, "northeast_of", "Genoa", "Casablanca", None,
     'Genoa was the birthplace of Columbus. Casablanca appears in Arabic as al-Dar al-Bayda.'),
    (1, "northeast_of", "Riyadh", "Kinshasa", None,
     'Riyadh is the Saudi capital and sits on a limestone plateau. Kinshasa is the largest French-speaking city in the world.'),
    (2, "northeast_of", "Mumbai", "Maputo", None,
     "Mumbai was built out from seven islands joined by land reclamation. Maputo is Mozambique's capital and its deepwater port."),
    (2, "northeast_of", "Islamabad", "Windhoek", None,
     "Islamabad lies against the Margalla Hills. Windhoek's name comes from the Afrikaans and German settlers who established it."),
    (2, "northeast_of", "Karachi", "Cape Town", None,
     'Karachi is the largest city in Pakistan. Cape Town developed around a Dutch resupply station for ships rounding Africa.'),
    (3, "northeast_of", "Porto", "Lima", None,
     "Porto gave its name to a fortified wine and to Portugal itself. Lima's historic centre is a UNESCO world heritage site."),
    (3, "northeast_of", "Faro", "La Paz", None,
     "Faro is the main city of the Algarve. La Paz shares Bolivia's capital functions with Sucre."),
    (3, "northeast_of", "Sarajevo", "Asuncion", None,
     'Sarajevo hosted the 1984 Winter Olympics. Asuncion is one of the oldest continuously inhabited cities in South America.'),
    (4, "northeast_of", "Madrid", "Santiago", None,
     "Madrid stands on the Meseta Central at about 650 metres. Santiago holds roughly forty percent of Chile's population."),
    (4, "northeast_of", "Reno", "Auckland", None,
     'Reno calls itself the biggest little city in the world. Auckland is built across an isthmus dotted with volcanic cones.'),
    (4, "northeast_of", "San Francisco", "Wellington", None,
     'San Francisco occupies the tip of a peninsula between a bay and the ocean. Wellington sits at the foot of the North Island.'),
    (5, "northeast_of", "Munich", "Valparaiso", None,
     "Munich lies on the Isar and grew rich on brewing and engineering. Valparaiso's funicular lifts connect its steep hillside neighbourhoods."),
    (5, "northeast_of", "Naples", "Recife", None,
     'Naples has one of the largest surviving historic centres in Europe. Recife is sometimes called the Venice of Brazil for its bridges.'),
    (5, "northeast_of", "Athens", "Salvador", None,
     'Athens gave democracy its name. Salvador was the arrival point for a large share of the transatlantic slave trade.'),
    # ---------------- northwest_of ----------------
    (1, "northwest_of", "Mexico City", "Quito", None,
     'Mexico City is built on a drained lake bed and is sinking into it. Quito was the first city to be listed as a world heritage site.'),
    (1, "northwest_of", "Warsaw", "Yerevan", None,
     "Warsaw's old town is a careful postwar reconstruction. Yerevan is one of the oldest continuously inhabited cities on earth."),
    (1, "northwest_of", "Zurich", "Jerusalem", None,
     "Zurich is Switzerland's financial centre though not its capital. Jerusalem holds sites sacred to three religions."),
    (2, "northwest_of", "Lyon", "Cairo", None,
     "Lyon sits where the Rhone meets the Saone and is known for its cuisine. Cairo's metropolitan area is the largest in Africa."),
    (2, "northwest_of", "Belgrade", "Abu Dhabi", None,
     'Belgrade stands at the confluence of the Sava and the Danube. Abu Dhabi occupies an island connected to the mainland by bridges.'),
    (2, "northwest_of", "Hong Kong", "Port Moresby", None,
     'Hong Kong returned to Chinese sovereignty in 1997. Port Moresby is the capital of Papua New Guinea.'),
    (3, "northwest_of", "Mumbai", "Perth", None,
     "Mumbai handles a large share of India's foreign trade. Perth is closer to Jakarta than to Sydney."),
    (3, "northwest_of", "Hanoi", "Sydney", None,
     "Hanoi marked its thousandth anniversary in 2010. Sydney's harbour bridge opened in 1932."),
    (3, "northwest_of", "Atlanta", "Fortaleza", None,
     "Atlanta rebuilt itself after being burned in 1864 and now runs the world's busiest airport. Fortaleza's beaches draw much of Brazil's domestic tourism."),
    (4, "northwest_of", "Salt Lake City", "Rio de Janeiro", None,
     "Salt Lake City was founded by Mormon pioneers in 1847. Rio de Janeiro was Brazil's capital until 1960."),
    (4, "northwest_of", "Yerevan", "Jakarta", None,
     'Yerevan looks out towards Mount Ararat. Jakarta lies on the island of Java at the mouth of the Ciliwung.'),
    (4, "northwest_of", "Bishkek", "Melbourne", None,
     'Bishkek is the Kyrgyz capital, laid out on a grid below the Tian Shan. Melbourne has topped liveability rankings repeatedly.'),
    (5, "northwest_of", "Halifax", "Windhoek", None,
     'Halifax has one of the largest natural harbours in the world. Windhoek lies roughly at the centre of Namibia.'),
    (5, "northwest_of", "Atlanta", "Recife", None,
     "Atlanta is the capital of Georgia and a centre of the American civil rights movement. Recife is the largest city in Brazil's northeast."),
    (5, "northwest_of", "Ulaanbaatar", "Wellington", None,
     "Ulaanbaatar is the coldest national capital in the world. Wellington sits at the foot of New Zealand's North Island."),
    # ---------------- southeast_of ----------------
    (1, "southeast_of", "Brisbane", "Hanoi", None,
     "Brisbane hosted the 2032 Olympic bid successfully. Hanoi is Vietnam's capital and its second-largest city."),
    (1, "southeast_of", "Beirut", "Malmo", None,
     "Beirut was rebuilt repeatedly after its civil war. Malmo is Sweden's third city."),
    (1, "southeast_of", "Riyadh", "Warsaw", None,
     "Riyadh's name derives from an Arabic word for gardens. Warsaw is Poland's capital and largest city."),
    (2, "southeast_of", "Abu Dhabi", "Minsk", None,
     "Abu Dhabi holds the bulk of the Emirates' hydrocarbon wealth. Minsk is Belarus's capital and was largely rebuilt after 1944."),
    (2, "southeast_of", "Antananarivo", "London", None,
     "Antananarivo's name means the city of a thousand. London is the largest city in the United Kingdom."),
    (2, "southeast_of", "Nairobi", "Edinburgh", None,
     "Nairobi has a national park within its city limits. Edinburgh's festival is the largest arts festival in the world."),
    (3, "southeast_of", "Fortaleza", "New York", None,
     "Fortaleza is one of Brazil's largest cities by population. New York's subway runs around the clock."),
    (3, "southeast_of", "Quito", "Salt Lake City", None,
     "Quito is Ecuador's capital and second-largest city. Salt Lake City lies beside a shallow, hypersaline lake."),
    (3, "southeast_of", "Dar es Salaam", "Edinburgh", None,
     "Dar es Salaam's name means haven of peace. Edinburgh has been Scotland's capital since the fifteenth century."),
    (4, "southeast_of", "Wellington", "Ho Chi Minh City", None,
     "Wellington is the southernmost capital city of any sovereign state. Ho Chi Minh City drives much of Vietnam's economic output."),
    (4, "southeast_of", "Montevideo", "Calgary", None,
     "Montevideo holds nearly half of Uruguay's population. Calgary sits where the Bow and Elbow rivers meet in Alberta."),
    (4, "southeast_of", "Sao Paulo", "Winnipeg", None,
     'Sao Paulo is the largest city in the southern hemisphere. Winnipeg lies at the confluence of the Red and Assiniboine rivers.'),
    (5, "southeast_of", "Buenos Aires", "San Diego", None,
     'Buenos Aires takes its character from waves of Italian and Spanish migration. San Diego has one of the mildest climates in the United States.'),
    (5, "southeast_of", "La Paz", "Salt Lake City", None,
     'La Paz sits in a canyon carved into the Altiplano. Salt Lake City hosted the Winter Olympics in 2002.'),
    (5, "southeast_of", "Perth", "Colombo", None,
     'Perth was founded as the Swan River Colony in 1829. Colombo has been a trading port since Roman times.'),
    # ---------------- southwest_of ----------------
    (1, "southwest_of", "Kampala", "Dubai", None,
     "Kampala's name is said to derive from the impala that once grazed its hills. Dubai is the most populous city in the United Arab Emirates."),
    (1, "southwest_of", "Casablanca", "Stockholm", None,
     "Casablanca's Hassan II Mosque has one of the tallest minarets in the world. Stockholm is built across fourteen islands."),
    (1, "southwest_of", "Dakar", "Milan", None,
     "Dakar hosted the finish of a famous rally for three decades. Milan is Italy's financial and fashion capital."),
    (2, "southwest_of", "Abu Dhabi", "Dushanbe", None,
     'Abu Dhabi means father of the gazelle. Dushanbe takes its name from the Tajik word for Monday, after its market day.'),
    (2, "southwest_of", "Dar es Salaam", "Islamabad", None,
     "Dar es Salaam was Tanzania's capital until Dodoma took the role. Islamabad was designed by a Greek planning firm."),
    (2, "southwest_of", "Harare", "Almaty", None,
     "Harare stands at about 1,500 metres, which keeps it temperate. Almaty was Kazakhstan's capital until 1997."),
    (3, "southwest_of", "Cape Town", "Pune", None,
     "Cape Town's harbour served ships on the route to the Indies. Pune sits on the Deccan plateau."),
    (3, "southwest_of", "Asuncion", "Faro", None,
     "Asuncion is Paraguay's capital and its largest city. Faro's lagoon system is a protected natural park."),
    (3, "southwest_of", "Salvador", "Lyon", None,
     "Salvador's Pelourinho district is a world heritage site. Lyon was the Roman capital of Gaul."),
    (4, "southwest_of", "Montevideo", "Algiers", None,
     "Montevideo's port has long been the country's main trade gateway. Algiers is known as Algiers the White for its buildings."),
    (4, "southwest_of", "Curitiba", "Paris", None,
     'Curitiba is the capital of the Brazilian state of Parana. Paris draws more visitors than any other European city.'),
    (4, "southwest_of", "Cape Town", "Almaty", None,
     "Cape Town's Company's Garden dates from the 1650s. Almaty sits at the foot of the Trans-Ili Alatau."),
    (5, "southwest_of", "Asuncion", "Dublin", None,
     "Asuncion was founded in 1537 and is called the mother of cities. Dublin has been Ireland's capital since the Anglo-Norman period."),
    (5, "southwest_of", "Montevideo", "Paris", None,
     "Montevideo's Rambla runs for more than twenty kilometres along the water. Paris is built around the Seine and its two islands."),
    (5, "southwest_of", "Windhoek", "Muscat", None,
     "Windhoek's central business district retains a number of colonial-era buildings. Muscat has served as a trading port between Arabia and the Indian Ocean for centuries."),
    # ---------------- Level 6: multi-hop ----------------
    (6, "north_of", "Helsinki", "Cape Town", "Warsaw",
     'Helsinki lies at a higher latitude than Warsaw, and Warsaw at a higher latitude than Cape Town.'),
    (6, "north_of", "Prague", "Tripoli", "Rome",
     'Prague stands nearer the Arctic than Rome, and Rome in turn stands nearer it than Tripoli.'),
    (6, "north_of", "Tbilisi", "Riyadh", "Baghdad",
     'Tbilisi is further up the meridian than Baghdad, and that city is further up it than Riyadh.'),
    (6, "south_of", "Cape Town", "Oslo", "Rome",
     'Cape Town lies further from the North Pole than Rome, and Rome further from it than Oslo.'),
    (6, "south_of", "Hong Kong", "Beijing", "Wuhan",
     'Hong Kong sits at a lower latitude than Wuhan in signed terms, and Wuhan lower than Beijing.'),
    (6, "south_of", "Nice", "Bergen", "Amsterdam",
     'Nice is nearer the Antarctic than Amsterdam, and Amsterdam in turn nearer it than Bergen.'),
    (6, "east_of", "Tokyo", "Beijing", "Seoul",
     'Tokyo has a more easterly longitude than Seoul, and Seoul a more easterly one than Beijing.'),
    (6, "east_of", "Jakarta", "Accra", "Nairobi",
     'Jakarta lies further round the globe toward the dateline than Nairobi, and Nairobi further than Accra.'),
    (6, "east_of", "Minsk", "Edinburgh", "Copenhagen",
     'Minsk keeps a later solar time than Copenhagen, and Copenhagen in turn a later one than Edinburgh.'),
    (6, "west_of", "London", "Minsk", "Berlin",
     'London has a more westerly longitude than Berlin, and Berlin a more westerly one than Minsk.'),
    (6, "west_of", "Bogota", "Khartoum", "Dakar",
     'Bogota lies further back along the meridians than Dakar, and Dakar further back than Khartoum.'),
    (6, "west_of", "Lyon", "Chisinau", "Vienna",
     'Lyon keeps an earlier solar time than Vienna, and that city an earlier one than Chisinau.'),
    (6, "northeast_of", "Bucharest", "Buenos Aires", "Tunis",
     'Bucharest is both at a higher latitude and a more easterly longitude than Tunis, and Tunis stands the same way to Buenos Aires.'),
    (6, "northeast_of", "Warsaw", "Montevideo", "Zurich",
     'Warsaw lies nearer the Arctic and further toward the dateline than Zurich, and Zurich in turn than Montevideo.'),
    (6, "northeast_of", "Berlin", "Madrid", "Lyon",
     'Berlin exceeds Lyon on both latitude and easting, and Lyon exceeds Madrid on both.'),
    (6, "northwest_of", "Moscow", "Perth", "Delhi",
     'Moscow is at a higher latitude but a more westerly longitude than Delhi, and Delhi stands the same way to Perth.'),
    (6, "northwest_of", "Budapest", "Beirut", "Istanbul",
     'Budapest lies nearer the Arctic and further back along the meridians than Istanbul, and Istanbul in turn than Beirut.'),
    (6, "northwest_of", "Oslo", "Odesa", "Warsaw",
     'Oslo exceeds Warsaw in latitude while trailing it in easting, and Warsaw relates to Odesa the same way.'),
    (6, "southeast_of", "Sydney", "Tashkent", "Jakarta",
     'Sydney lies further from the North Pole but more easterly than Jakarta, and Jakarta stands the same way to Tashkent.'),
    (6, "southeast_of", "Naples", "Dublin", "Lyon",
     'Naples is nearer the Antarctic and further toward the dateline than Lyon, and Lyon in turn than Dublin.'),
    (6, "southeast_of", "Chennai", "Karachi", "Pune",
     'Chennai trails Pune in latitude while exceeding it in easting, and Pune relates to Karachi the same way.'),
    (6, "southwest_of", "Casablanca", "Turin", "Valencia",
     'Casablanca lies further from the North Pole and more westerly than Valencia, and Valencia stands the same way to Turin.'),
    (6, "southwest_of", "Venice", "St Petersburg", "Warsaw",
     'Venice is nearer the Antarctic and further back along the meridians than Warsaw, and Warsaw in turn than St Petersburg.'),
    (6, "southwest_of", "Guayaquil", "Caracas", "Bogota",
     'Guayaquil trails Bogota on both latitude and easting, and Bogota trails Caracas on both.'),
]
