"""One identifying clause per city, carrying no hint of a bearing.

Cardinal items differ from topological ones in what may be said. Naming a
city's country is fine here -- knowing that Oslo is Norwegian and Rome Italian
is exactly the geographic knowledge the item is meant to test. What may never
appear is the direction itself, in any form: compass words, map metaphors,
clock bearings, references to the sun, the poles, the equator, or latitude and
longitude. Those made the old corpus answerable without knowing anything, and
left the task saturated at 97-100%.

Clauses for cities that also appear in the topological catalogue are reused
from there, so a place is described the same way wherever it turns up.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from topo_identity import IDENTITY as _TOPO           # noqa: E402

NEW = {
 "abu dhabi": "Abu Dhabi is the capital of the United Arab Emirates and holds most of its oil reserves",
 "addis ababa": "Addis Ababa hosts the headquarters of the African Union",
 "algiers": "Algiers rises in white tiers above its bay",
 "almaty": "Almaty was Kazakhstan's capital until 1997",
 "amman": "Amman is built over a set of hills the Romans called Philadelphia",
 "anchorage": "Anchorage is the largest city in Alaska by a wide margin",
 "ankara": "Ankara replaced Istanbul as Turkey's capital in 1923",
 "antananarivo": "Antananarivo is the Malagasy capital, spread across a ridge of hills",
 "ashgabat": "Ashgabat was rebuilt in white marble after an earthquake in 1948",
 "asuncion": "Asuncion was founded in 1537 and is called the mother of cities",
 "auckland": "Auckland is built across an isthmus dotted with volcanic cones",
 "baghdad": "Baghdad was founded in 762 as a perfectly round city",
 "baku": "Baku's old town is enclosed by medieval walls above the Caspian",
 "beijing": "Beijing has been an imperial seat since the Ming dynasty",
 "beirut": "Beirut occupies a headland projecting into the Mediterranean",
 "belgrade": "Belgrade stands where the Sava joins the Danube",
 "bergen": "Bergen was Norway's largest settlement through the Hanseatic period",
 "birmingham": "Birmingham was the workshop of Britain's industrial revolution",
 "bishkek": "Bishkek is the Kyrgyz capital, laid out on a grid below the Tian Shan",
 "bogota": "Bogota is one of the highest capital cities in the world",
 "bratislava": "Bratislava sits on the Danube within sight of two international borders",
 "brisbane": "Brisbane straddles a looping river in Queensland",
 "bucharest": "Bucharest was once nicknamed the Paris of the Balkans",
 "buenos aires": "Buenos Aires takes its character from waves of Italian and Spanish migration",
 "caracas": "Caracas lies in a narrow valley cut off from the Caribbean by a coastal range",
 "cardiff": "Cardiff grew rich exporting Welsh coal",
 "chengdu": "Chengdu is known for its spiced cuisine and its panda reserve",
 "chennai": "Chennai grew around a British trading fort established in 1639",
 "chisinau": "Chisinau is the Moldovan capital and its largest city",
 "colombo": "Colombo is Sri Lanka's commercial capital and largest port",
 "curitiba": "Curitiba pioneered bus rapid transit in the 1970s",
 "dakar": "Dakar occupies a peninsula that is the westernmost point of continental Africa",
 "damascus": "Damascus claims one of the longest records of continuous settlement anywhere",
 "dar es salaam": "Dar es Salaam's name means haven of peace",
 "darwin": "Darwin was rebuilt after a cyclone destroyed most of it in 1974",
 "dhaka": "Dhaka is one of the most densely populated cities in the world",
 "doha": "Doha hosted a football World Cup in 2022",
 "dubai": "Dubai built a global transport hub on what was a pearling coast",
 "dushanbe": "Dushanbe takes its name from the Tajik word for Monday, after its market day",
 "edinburgh": "Edinburgh's festival is the largest arts festival in the world",
 "edmonton": "Edmonton has one of the largest shopping complexes ever built",
 "faro": "Faro is the main city of the Algarve and its lagoon is a protected park",
 "fortaleza": "Fortaleza is a Brazilian state capital and a major fishing centre",
 "genoa": "Genoa was a maritime republic that rivalled Venice for centuries",
 "gothenburg": "Gothenburg is Sweden's second city and the site of its largest port",
 "guayaquil": "Guayaquil is Ecuador's largest city and its principal port",
 "halifax": "Halifax has one of the largest natural harbours in the world",
 "hanoi": "Hanoi marked its thousandth anniversary in 2010",
 "harare": "Harare was known as Salisbury until 1982",
 "havana": "Havana's seafront promenade runs for eight kilometres",
 "ho chi minh city": "Ho Chi Minh City was known as Saigon and drives much of Vietnam's output",
 "hong kong": "Hong Kong returned to Chinese sovereignty in 1997",
 "islamabad": "Islamabad was purpose-built in the 1960s to replace Karachi as Pakistan's capital",
 "istanbul": "Istanbul straddles the Bosphorus and was capital of two empires",
 "jakarta": "Jakarta is subsiding fast enough that a replacement capital is being built",
 "jerusalem": "Jerusalem holds sites sacred to three religions",
 "kabul": "Kabul sits in a high valley ringed by the Hindu Kush",
 "kampala": "Kampala replaced Entebbe as Uganda's capital at independence",
 "karachi": "Karachi is Pakistan's financial centre and its window on the Arabian Sea",
 "kathmandu": "Kathmandu lies in a bowl-shaped valley in Nepal",
 "khartoum": "Khartoum stands where the Blue and White Niles converge",
 "kingston": "Kingston is Jamaica's capital and holds a large natural harbour",
 "kinshasa": "Kinshasa is the largest French-speaking city in the world",
 "kolkata": "Kolkata was the capital of British India until 1911",
 "kuala lumpur": "Kuala Lumpur grew from a tin-mining settlement into Malaysia's capital",
 "kuwait city": "Kuwait City was rebuilt rapidly on oil revenue after the 1950s",
 "kyiv": "Kyiv was the centre of the medieval Rus federation",
 "la paz": "La Paz is the highest seat of government anywhere",
 "lima": "Lima was founded by Pizarro in 1535 and remains Peru's capital",
 "london": "London developed along a tidal stretch of the Thames",
 "luanda": "Luanda ranks among the costliest cities on its continent for expatriate workers",
 "malmo": "Malmo is joined to Copenhagen by the Oresund bridge and tunnel",
 "managua": "Managua sits beside a lake of the same name and has been rebuilt twice after earthquakes",
 "manila": "Manila anchors a metropolitan region of over thirteen million",
 "maputo": "Maputo was called Lourenco Marques until 1976",
 "mexico city": "Mexico City is built on a drained lake bed and is sinking into it",
 "minsk": "Minsk was largely rebuilt after 1944 in monumental style",
 "mogadishu": "Mogadishu was a major medieval trading port",
 "montevideo": "Montevideo's Rambla runs for more than twenty kilometres along the water",
 "moscow": "Moscow's metro stations were built as public palaces",
 "muscat": "Muscat's old quarter is enclosed by Portuguese-built forts",
 "new york": "New York anchors the largest metropolitan economy in the United States",
 "nice": "Nice's seafront promenade was funded by British visitors in the 1820s",
 "nicosia": "Nicosia is the last divided capital in Europe",
 "odesa": "Odesa was founded as a free port by imperial decree in 1794",
 "osaka": "Osaka was the merchant capital of Japan for centuries",
 "ottawa": "Ottawa was chosen as a compromise capital by Queen Victoria",
 "panama city": "Panama City guards one end of an interoceanic waterway",
 "perth": "Perth is among the most isolated large cities anywhere",
 "phnom penh": "Phnom Penh sits where three rivers meet",
 "port moresby": "Port Moresby is the capital of Papua New Guinea",
 "porto": "Porto gave its name to a fortified wine and to Portugal itself",
 "pune": "Pune was the seat of the Maratha empire",
 "pyongyang": "Pyongyang was rebuilt almost entirely after 1953",
 "quebec city": "Quebec City retains the only fortified walls in North America outside Mexico",
 "quito": "Quito was among the first places inscribed as a world heritage site",
 "recife": "Recife is built across islands and waterways and is called the Venice of Brazil",
 "reno": "Reno calls itself the biggest little city in the world",
 "reykjavik": "Reykjavik is heated almost entirely by geothermal water",
 "riga": "Riga's old town holds a dense collection of art nouveau buildings",
 "rio de janeiro": "Rio de Janeiro was Brazil's capital until 1960",
 "riyadh": "Riyadh grew from a walled desert settlement into a city of millions",
 "salt lake city": "Salt Lake City was founded by Mormon pioneers in 1847",
 "salvador": "Salvador was Brazil's first colonial capital",
 "san antonio": "San Antonio grew around a mission that became a famous battle site",
 "san juan": "San Juan is among the oldest European-founded cities in the Americas",
 "santiago": "Santiago holds roughly forty percent of Chile's population",
 "sao paulo": "Sao Paulo is the largest city in the southern hemisphere",
 "sapporo": "Sapporo hosts an annual festival of monumental snow sculptures",
 "sarajevo": "Sarajevo hosted the 1984 Winter Olympics",
 "seoul": "Seoul has been Korea's capital since the Joseon dynasty",
 "shanghai": "Shanghai handles the busiest container port in the world",
 "singapore": "Singapore is a city-state that separated from Malaysia in 1965",
 "sofia": "Sofia has been settled since Thracian times and is named for a basilica",
 "st petersburg": "St Petersburg was built on marshland by imperial decree in 1703",
 "surabaya": "Surabaya is Indonesia's second city and a major naval base",
 "suva": "Suva is the Fijian capital, on the island of Viti Levu",
 "taipei": "Taipei's tallest tower was briefly the world's highest building",
 "tallinn": "Tallinn's walled centre is among the best preserved in the Baltic",
 "tashkent": "Tashkent was rebuilt on a Soviet plan after an earthquake in 1966",
 "tbilisi": "Tbilisi was founded around its sulphur springs",
 "tehran": "Tehran sprawls at the foot of the Alborz range",
 "thimphu": "Thimphu is one of the few capitals without traffic lights",
 "tijuana": "Tijuana handles one of the busiest land border crossings in the world",
 "tirana": "Tirana had its grey apartment blocks painted in bright colours in the 2000s",
 "tripoli": "Tripoli was founded by the Phoenicians as Oea",
 "tunis": "Tunis grew up beside the ruins of Carthage",
 "turin": "Turin was Italy's first capital after unification",
 "ulaanbaatar": "Ulaanbaatar is the coldest national capital in the world",
 "valencia": "Valencia is Spain's third city and the home of paella",
 "valparaiso": "Valparaiso's funicular lifts connect its steep hillside neighbourhoods",
 "vientiane": "Vientiane is the Lao capital and sits on the Mekong",
 "vilnius": "Vilnius has one of the largest surviving medieval old towns in its region",
 "vladivostok": "Vladivostok is the terminus of the Trans-Siberian Railway",
 "washington": "Washington was laid out by Pierre L'Enfant in 1791",
 "wellington": "Wellington is the seat of New Zealand's parliament and known for its wind",
 "windhoek": "Windhoek's architecture still carries traces of its German colonial period",
 "windsor": "Windsor is Canada's automotive manufacturing centre",
 "winnipeg": "Winnipeg lies at the confluence of the Red and Assiniboine rivers",
 "wuhan": "Wuhan was formed by merging three cities across the Yangtze",
 "yangon": "Yangon was Myanmar's capital until 2006 and holds the Shwedagon Pagoda",
 "yerevan": "Yerevan is one of the oldest continuously inhabited cities on earth",
 "zagreb": "Zagreb was formed from two rival medieval settlements on neighbouring hills",
}

CITY = dict(NEW)
for _k, _v in _TOPO.items():
    _key = (_k.lower().replace("city of ", "")
                     .replace("city and county of ", "").strip())
    CITY.setdefault(_key, _v)
