"""One identifying clause per city, carrying no hint of a bearing.

Cardinal items differ from topological ones in what may be said. Naming a
city's country is fine here -- knowing that Oslo is Norwegian and Rome Italian
is exactly the geographic knowledge the item is meant to test. What may never
appear is the direction itself, in any form: compass words, map metaphors,
clock bearings, references to the sun, the poles, the equator, or latitude and
longitude. Those made the old corpus answerable without knowing anything, and
left the task saturated at 97-100%.

Clauses for cities that also appear in the topological catalogue are reused
from there, so a place is described the same way wherever it turns up.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from topo_identity import IDENTITY as _TOPO           # noqa: E402

NEW = {
 "abu dhabi": "Abu Dhabi is the capital of the United Arab Emirates and holds most of its oil reserves",
 "addis ababa": "Addis Ababa hosts the headquarters of the African Union",
 "algiers": "Algiers rises in white tiers above its bay",
 "almaty": "Almaty was Kazakhstan's capital until 1997",
 "amman": "Amman is built over a set of hills the Romans called Philadelphia",
 "anchorage": "Anchorage is the largest city in Alaska by a wide margin",
 "ankara": "Ankara replaced Istanbul as Turkey's capital in 1923",
 "antananarivo": "Antananarivo is the Malagasy capital, spread across a ridge of hills",
 "ashgabat": "Ashgabat was rebuilt in white marble after an earthquake in 1948",
 "asuncion": "Asuncion was founded in 1537 and is called the mother of cities",
 "auckland": "Auckland is built across an isthmus dotted with volcanic cones",
 "baghdad": "Baghdad was founded in 762 as a perfectly round city",
 "baku": "Baku's old town is ringed by medieval walls above the Caspian",
 "beijing": "Beijing has been an imperial seat since the Ming dynasty",
 "beirut": "Beirut occupies a headland projecting into the Mediterranean",
 "belgrade": "Belgrade stands where the Sava joins the Danube",
 "bergen": "Bergen was Norway's largest settlement through the Hanseatic period",
 "birmingham": "Birmingham was the workshop of Britain's industrial revolution",
 "bishkek": "Bishkek is the Kyrgyz capital, laid out on a grid below the Tian Shan",
 "bogota": "Bogota is one of the highest capital cities in the world",
 "bratislava": "Bratislava sits on the Danube and was known as Pressburg until 1919",
 "brisbane": "Brisbane straddles a looping river in Queensland",
 "bucharest": "Bucharest was once nicknamed the Paris of the Balkans",
 "buenos aires": "Buenos Aires takes its character from waves of Italian and Spanish migration",
 "caracas": "Caracas lies in a narrow valley cut off from the Caribbean by a coastal range",
 "cardiff": "Cardiff grew rich exporting Welsh coal",
 "chengdu": "Chengdu is known for its spiced cuisine and its panda reserve",
 "chennai": "Chennai grew around a British trading fort established in 1639",
 "chisinau": "Chisinau is the Moldovan capital and its largest city",
 "colombo": "Colombo is Sri Lanka's commercial capital and largest port",
 "curitiba": "Curitiba pioneered bus rapid transit in the 1970s",
 "dakar": "Dakar occupies a peninsula that is the westernmost point of continental Africa",
 "damascus": "Damascus claims one of the longest records of continuous settlement anywhere",
 "dar es salaam": "Dar es Salaam's name means haven of peace",
 "darwin": "Darwin was rebuilt after a cyclone destroyed most of it in 1974",
 "dhaka": "Dhaka is one of the most densely populated cities in the world",
 "doha": "Doha hosted a football World Cup in 2022",
 "dubai": "Dubai built a global transport hub on what was a pearling coast",
 "dushanbe": "Dushanbe takes its name from the Tajik word for Monday, after its market day",
 "edinburgh": "Edinburgh's festival is the largest arts festival in the world",
 "edmonton": "Edmonton has one of the largest shopping complexes ever built",
 "faro": "Faro is the main city of the Algarve and its lagoon is a protected park",
 "fortaleza": "Fortaleza is a Brazilian state capital and a major fishing centre",
 "genoa": "Genoa was a maritime republic that rivalled Venice for centuries",
 "gothenburg": "Gothenburg is Sweden's second city and the site of its largest port",
 "guayaquil": "Guayaquil is Ecuador's largest city and its principal port",
 "halifax": "Halifax has one of the largest natural harbours in the world",
 "hanoi": "Hanoi marked its thousandth anniversary in 2010",
 "harare": "Harare was known as Salisbury until 1982",
 "havana": "Havana's seafront promenade runs for eight kilometres",
 "ho chi minh city": "Ho Chi Minh City was known as Saigon and drives much of Vietnam's output",
 "hong kong": "Hong Kong returned to Chinese sovereignty in 1997",
 "islamabad": "Islamabad was purpose-built in the 1960s to replace Karachi as Pakistan's capital",
 "istanbul": "Istanbul straddles the Bosphorus and was capital of two empires",
 "jakarta": "Jakarta is subsiding fast enough that a replacement capital is being built",
 "jerusalem": "Jerusalem holds sites sacred to three religions",
 "kabul": "Kabul sits in a high valley ringed by the Hindu Kush",
 "kampala": "Kampala replaced Entebbe as Uganda's capital at independence",
 "karachi": "Karachi is Pakistan's financial centre and its window on the Arabian Sea",
 "kathmandu": "Kathmandu lies in a bowl-shaped valley in Nepal",
 "khartoum": "Khartoum stands where the Blue and White Niles converge",
 "kingston": "Kingston is Jamaica's capital and holds a large natural harbour",
 "kinshasa": "Kinshasa is the largest French-speaking city in the world",
 "kolkata": "Kolkata was the capital of British India until 1911",
 "kuala lumpur": "Kuala Lumpur grew from a tin-mining settlement into Malaysia's capital",
 "kuwait city": "Kuwait City was rebuilt rapidly on oil revenue after the 1950s",
 "kyiv": "Kyiv was the centre of the medieval Rus federation",
 "la paz": "La Paz is the highest seat of government anywhere",
 "lima": "Lima was founded by Pizarro in 1535 and remains Peru's capital",
 "london": "London developed along a tidal stretch of the Thames",
 "luanda": "Luanda ranks among the costliest cities on its continent for expatriate workers",
 "malmo": "Malmo is joined to Copenhagen by the Oresund bridge and tunnel",
 "managua": "Managua sits beside a lake of the same name and has been rebuilt twice after earthquakes",
 "manila": "Manila anchors a metropolitan region of over thirteen million",
 "maputo": "Maputo was called Lourenco Marques until 1976",
 "mexico city": "Mexico City is built on a drained lake bed and is sinking into it",
 "minsk": "Minsk was largely rebuilt after 1944 in monumental style",
 "mogadishu": "Mogadishu was a major medieval trading port",
 "montevideo": "Montevideo's Rambla runs for more than twenty kilometres along the water",
 "moscow": "Moscow's metro stations were built as public palaces",
 "muscat": "Muscat's old quarter is guarded by Portuguese-built forts",
 "new york": "New York anchors the largest metropolitan economy in the United States",
 "nice": "Nice's seafront promenade was funded by British visitors in the 1820s",
 "nicosia": "Nicosia is the last divided capital in Europe",
 "odesa": "Odesa was founded as a free port by imperial decree in 1794",
 "osaka": "Osaka was the merchant capital of Japan for centuries",
 "ottawa": "Ottawa was chosen as a compromise capital by Queen Victoria",
 "panama city": "Panama City guards one end of an interoceanic waterway",
 "perth": "Perth is among the most isolated large cities anywhere",
 "phnom penh": "Phnom Penh sits where three rivers meet",
 "port moresby": "Port Moresby is the capital of Papua New Guinea",
 "porto": "Porto gave its name to a fortified wine and to Portugal itself",
 "pune": "Pune was the seat of the Maratha empire",
 "pyongyang": "Pyongyang was rebuilt almost entirely after 1953",
 "quebec city": "Quebec City retains the only fortified walls in North America outside Mexico",
 "quito": "Quito was among the first places inscribed as a world heritage site",
 "recife": "Recife is built across islands and waterways and is called the Venice of Brazil",
 "reno": "Reno calls itself the biggest little city in the world",
 "reykjavik": "Reykjavik is heated almost entirely by geothermal water",
 "riga": "Riga's old town holds a dense collection of art nouveau buildings",
 "rio de janeiro": "Rio de Janeiro was Brazil's capital until 1960",
 "riyadh": "Riyadh grew from a walled desert settlement into a city of millions",
 "salt lake city": "Salt Lake City was founded by Mormon pioneers in 1847",
 "salvador": "Salvador was Brazil's first colonial capital",
 "san antonio": "San Antonio grew around a mission that became a famous battle site",
 "san juan": "San Juan is among the oldest European-founded cities in the Americas",
 "santiago": "Santiago holds roughly forty percent of Chile's population",
 "sao paulo": "Sao Paulo is the largest city in the southern hemisphere",
 "sapporo": "Sapporo hosts an annual festival of monumental snow sculptures",
 "sarajevo": "Sarajevo hosted the 1984 Winter Olympics",
 "seoul": "Seoul has been Korea's capital since the Joseon dynasty",
 "shanghai": "Shanghai handles the busiest container port in the world",
 "singapore": "Singapore is a city-state that separated from Malaysia in 1965",
 "sofia": "Sofia has been settled since Thracian times and is named for a basilica",
 "st petersburg": "St Petersburg was built on marshland by imperial decree in 1703",
 "surabaya": "Surabaya is Indonesia's second city and a major naval base",
 "suva": "Suva is the Fijian capital, on the island of Viti Levu",
 "taipei": "Taipei's tallest tower was briefly the world's highest building",
 "tallinn": "Tallinn's walled centre is among the best preserved in the Baltic",
 "tashkent": "Tashkent was rebuilt on a Soviet plan after an earthquake in 1966",
 "tbilisi": "Tbilisi was founded around its sulphur springs",
 "tehran": "Tehran sprawls at the foot of the Alborz range",
 "thimphu": "Thimphu is one of the few capitals without traffic lights",
 "tijuana": "Tijuana handles one of the busiest land border crossings in the world",
 "tirana": "Tirana had its grey apartment blocks painted in bright colours in the 2000s",
 "tripoli": "Tripoli was founded by the Phoenicians as Oea",
 "tunis": "Tunis grew up beside the ruins of Carthage",
 "turin": "Turin was Italy's first capital after unification",
 "ulaanbaatar": "Ulaanbaatar is the coldest national capital in the world",
 "valencia": "Valencia is Spain's third city and the home of paella",
 "valparaiso": "Valparaiso's funicular lifts connect its steep hillside neighbourhoods",
 "vientiane": "Vientiane is the Lao capital and sits on the Mekong",
 "vilnius": "Vilnius has one of the largest surviving medieval old towns in its region",
 "vladivostok": "Vladivostok is the terminus of the Trans-Siberian Railway",
 "washington": "Washington was laid out by Pierre L'Enfant in 1791",
 "wellington": "Wellington is the seat of New Zealand's parliament and known for its wind",
 "windhoek": "Windhoek's architecture still carries traces of its German colonial period",
 "windsor": "Windsor is Canada's automotive manufacturing centre",
 "winnipeg": "Winnipeg lies at the confluence of the Red and Assiniboine rivers",
 "wuhan": "Wuhan was formed by merging three cities across the Yangtze",
 "yangon": "Yangon was Myanmar's capital until 2006 and holds the Shwedagon Pagoda",
 "yerevan": "Yerevan is one of the oldest continuously inhabited cities on earth",
 "zagreb": "Zagreb was formed from two rival medieval settlements on neighbouring hills",
}


# Clauses for the ingested cities. Written by a generator, screened for the
# phrasing that would state a bearing, and kept verbatim otherwise.
NEW.update({
    'aba': 'the massive Ariaria market is a crucial hub for local manufacturing and trade',
    'agra': 'a massive white marble mausoleum is widely considered a masterpiece of world architecture',
    'aktau': 'the urban layout uses a unique block-numbering system instead of street names',
    'aktobe': 'a prominent planetarium has hosted visitors for decades',
    'al ain': 'an ancient falaj irrigation system continues to support massive date palm oases',
    'aleppo': 'a massive covered bazaar was historically a major hub of global trade',
    'alofi': 'the settlement relies heavily on rainwater harvesting due to a lack of surface water',
    'ambato': 'a massive festival celebrates local flowers and fruits',
    'ambon': 'the local economy historically centered entirely on the spice trade',
    'andijan': 'the founder of the Mughal Empire was born in this ancient settlement',
    'apia': 'a prominent museum is dedicated to the author of Treasure Island',
    'aqaba': 'a massive flagpole dominates the waterfront',
    'arecibo': 'a massive radio telescope was historically a major scientific landmark',
    'arequipa': 'buildings are predominantly constructed from a highly distinctive white volcanic stone',
    'arusha': 'the settlement serves as the primary staging point for major safari expeditions',
    'atyrau': 'a pedestrian bridge symbolically connects two different continents',
    'auki': 'artificial islands constructed from coral rock support local fishing communities',
    'bacolod': 'a massive festival features participants wearing intensely smiling masks',
    'bagan': 'thousands of ancient brick stupas dot the arid landscape',
    'bago': 'a massive reclining Buddha statue is a major pilgrimage site',
    'baguio': 'the cool climate makes it a highly popular summer retreat',
    'balikpapan': 'oil refinement and timber processing form the core of the economy',
    'balkanabat': 'oil extraction and processing defined the early growth of this settlement',
    'bandung': 'art deco architecture features heavily in the older urban neighborhoods',
    'banjarmasin': 'an extensive network of canals hosts a bustling floating market',
    'bariloche': 'the local architecture heavily mimics traditional alpine Swiss chalets',
    'barnaul': 'silver smelting drove the early economy before agriculture took over',
    'basra': 'an extensive network of canals once earned it a highly romanticized reputation',
    'batumi': 'a distinctive tower features a built-in Ferris wheel in its upper architecture',
    'bayamon': 'a local park features historic train cars converted into a museum',
    'beersheba': 'the local university focuses heavily on arid environment research',
    'belem': 'a massive outdoor market is highly famous for selling exotic Amazonian ingredients',
    'belmopan': 'the government complex was constructed strictly to withstand severe hurricanes',
    'belo horizonte': 'the urban layout was highly planned before construction began',
    'bhopal': 'a tragic industrial accident severely impacted the local community',
    'bintulu': 'massive natural gas processing facilities dominate the industrial sector',
    'boa vista': 'the urban layout was designed in a distinct radial pattern',
    'bokhtar': 'the local museum displays a famous diorama of local agricultural history',
    'brasov': 'a massive gothic church dominates the historic medieval center',
    'bujumbura': 'french colonial architecture mixes with modern government buildings',
    'bukavu': 'art deco architecture features prominently among the older buildings',
    'bukhara': 'a massive brick minaret impressed Genghis Khan so much that he spared it from destruction',
    'cagayan de oro': 'whitewater rafting on the local river is a major economic driver',
    'caguas': 'a botanical garden features ruins of a historic sugar mill',
    'cajamarca': 'the local dairy industry is widely considered the best in the region',
    'calabar': 'a prominent festival features elaborate masquerades and street parades',
    'camagüey': 'the street layout is famously labyrinthine to confuse historical pirates',
    'campo grande': 'the local culture is deeply influenced by traditional cattle ranching',
    'cap-haitien': 'a massive mountaintop fortress dominates the surrounding landscape',
    'cebu city': 'a highly ornate wooden cross marks a major historical religious conversion',
    'chandigarh': 'the urban layout was entirely designed by a highly famous modernist architect',
    'chiang mai': 'elaborate paper lanterns are released into the sky during an annual festival',
    'chiang rai': 'an intensely intricate all-white temple is a major contemporary art piece',
    'chiclayo': 'a massive market features a dedicated section for traditional medicinal herbs',
    'cluj-napoca': 'a prominent university drives a highly active local technology sector',
    'cobija': 'the local economy relies heavily on harvesting Brazil nuts from the surrounding jungle',
    'cochabamba': 'a massive statue of Christ overlooks the urban grid',
    'coimbatore': 'the local economy relies heavily on intense textile machinery manufacturing',
    'constanta': 'a highly ornate abandoned casino sits directly on the waterfront',
    'cordoba, argentina': 'a highly renowned historic university was founded here in the seventeenth century',
    'cuenca, ecuador': 'panama hats are a highly famous local manufactured export',
    'cuiaba': 'the settlement is widely recognized as one of the hottest urban centers on the continent',
    'cusco': 'massive, perfectly fitted Inca stone walls serve as foundations for colonial buildings',
    'dammam': 'the local economy is overwhelmingly dominated by the petroleum industry',
    'dangriga': 'the settlement is widely considered the cultural heart of the Garifuna people',
    'davao city': 'a specialized facility focuses on breeding and protecting rare eagles',
    'david, panama': 'the settlement serves as a major commercial hub for agricultural distribution',
    'daşoguz': 'elaborate traditional carpets are woven by hand in local workshops',
    'denpasar': 'elaborate stone carvings decorate local intersections and public spaces',
    'derbent': 'ancient stone walls built by the Sasanian Empire still protect the historic citadel',
    'dodoma': 'a highly planned urban grid was designed to promote pedestrian movement',
    'eilat': 'an underwater observatory provides direct views of a highly active coral reef',
    'eldoret': 'the high altitude makes it a legendary training ground for long-distance runners',
    'enugu': 'coal mining earned it the nickname of the coal city',
    'erbil': 'a massive ancient citadel sits atop a prominent mound in the center',
    'esmeraldas': 'the local culture features a distinct style of traditional marimba music',
    'faisalabad': 'the local economy is overwhelmingly dominated by the textile manufacturing industry',
    'fergana': 'wide tree-lined avenues reflect its origins as a nineteenth-century garrison town',
    'freeport': 'a major perfume factory operates alongside extensive duty-free commerce',
    'funafuti': 'the local airstrip is frequently used as an open public recreational space',
    'ganja': 'the poet Nizami Ganjavi is commemorated with a grand monumental tomb',
    'garissa': 'a major solar power plant was recently constructed to boost local energy',
    'general santos': 'the local economy is overwhelmingly dominated by the tuna fishing industry',
    'goiania': 'art deco architecture features heavily in the older urban neighborhoods',
    'goma': 'volcanic rock is frequently used as a local building material',
    'granada, nicaragua': 'horse-drawn carriages remain a highly common form of local transport',
    'grozny': 'a massive reconstruction effort replaced heavily damaged blocks with glass skyscrapers',
    'guantanamo': 'the local architecture features significant French colonial influences',
    'gwadar': 'a massive deepwater facility is the focus of intense international investment',
    'gyumri': 'traditional black tuff stone gives the historic district a distinctive dark appearance',
    'hagåtña': 'ancient latte stones are displayed prominently in a central park',
    'haifa': 'a massive terraced garden complex is a highly prominent local landmark',
    'hama': 'massive wooden water wheels still operate along the river',
    'hat yai': 'a major commercial hub relies heavily on shopping tourism',
    'holguin': 'a massive wooden cross overlooks the urban grid from a prominent hill',
    'homs': 'the local culinary scene is highly famous for unique traditional sweets',
    'honiara': 'wrecked World War II machinery is heavily scattered across the landscape',
    'hua hin': 'a historic railway station features a highly ornate royal waiting room',
    'huancayo': 'a traditional craft market is famous for highly intricate carved gourds',
    'hyderabad, pakistan': 'the local climate is heavily moderated by distinct evening breezes',
    'iasi': 'a highly elaborate cultural palace dominates the central square',
    'ibadan': 'a highly renowned university was founded here in the mid-twentieth century',
    'ibarra': 'the local craft industry is highly famous for intricate wood carvings',
    'iloilo city': 'historic mansions reflect a wealthy past built on the sugar industry',
    'ilorin': 'a traditional pottery industry produces distinctive terracotta vessels',
    'imperatriz': 'the lumber and furniture industries form the core of the economy',
    'indore': 'a massive palace features highly elaborate mirror work and architecture',
    'ipoh': 'the settlement grew rapidly due to a massive historical tin mining boom',
    'iquitos': 'the settlement is entirely inaccessible by terrestrial road networks',
    'irbid': 'the local economy relies heavily on an intense concentration of universities',
    'irkutsk': 'traditional wooden architecture with intricate lace-like carvings lines the older streets',
    'jacmel': 'the local carnival features highly elaborate papier-mâché masks',
    'jaipur': 'the historic district buildings are painted a highly uniform pink color',
    'jalal-abad': 'thermal springs and mineral waters have drawn visitors for centuries',
    'jeddah': 'historic buildings in the old quarter are constructed from highly distinctive coral rock',
    'johor bahru': 'a massive causeway facilitates intense daily commuter traffic',
    'jos': 'a significantly cooler climate supports a unique plateau ecosystem',
    'juliaca': 'the local economy is heavily dominated by informal textile trading',
    'kaduna': 'cotton and textile manufacturing historically drove the local economy',
    'kakamega': 'a remnant patch of ancient tropical rainforest is highly protected',
    'kananga': 'the town serves as a crucial transit hub for agricultural products',
    'kano': 'centuries-old dye pits continue to process indigo fabrics using traditional methods',
    'kanpur': 'the local economy historically centered on intense leather processing',
    'karakol': 'a wooden Russian Orthodox church was constructed entirely without nails',
    'karbala': 'a highly elaborate shrine draws millions of participants during an annual pilgrimage',
    'khabarovsk': 'ice sculptures fill the central squares during the freezing winter months',
    'khiva': 'mud-brick walls entirely enclose the intensely preserved historic inner town',
    'khon kaen': 'a major university focuses heavily on developing regional agricultural techniques',
    'khorugh': 'a high-altitude botanical garden cultivates plants adapted to extreme conditions',
    'khujand': 'a historical fortress overlooks the river that flows through the center',
    'kigali': 'the streets are famously kept spotless through a mandatory community cleaning day',
    'kigoma': 'a historic railway terminus connects to a major inland water route',
    'kikwit': 'traditional masked dances are a hallmark of local cultural festivals',
    'kisangani': 'a historic railway bypasses a series of unnavigable river cataracts',
    'kisumu': 'a clock tower commemorates a prominent local merchant',
    'kochi': 'massive, highly distinctive cantilevered fishing nets line the waterfront',
    'kokshetau': 'local food industries focus heavily on dairy and grain processing',
    'kolonia': 'heavy rainfall supports a highly lush, intensely green environment',
    'kolwezi': 'massive open-pit mines dominate the immediate surroundings',
    'koror': 'a specialized facility studies highly unique jellyfish populations',
    'kota kinabalu': 'a prominent mosque appears to float on a constructed lagoon',
    'krasnoyarsk': 'the local hydroelectric dam is depicted on the ten-ruble banknote',
    'kuching': 'numerous statues and monuments celebrate the local feline namesake',
    'kulob': 'a grand mausoleum commemorates a prominent fourteenth-century Sufi poet',
    'kumasi': 'the golden stool is considered the sacred unifying symbol of the traditional kingdom',
    'kutaisi': 'the restored Bagrati Cathedral dominates the skyline from its hilltop position',
    'kyzylorda': 'the town features a dam constructed to manage river ice and flooding',
    'la romana': "a meticulously recreated sixteenth-century Mediterranean village serves as an artists' colony",
    'lashio': 'the settlement is the terminus of a famous historical supply road',
    'latakia': 'the local economy relies heavily on intensive agricultural exports and shipping',
    'leon, nicaragua': 'a massive cathedral roof provides sweeping panoramic views',
    'les cayes': 'vetiver oil production is a significant component of the local economy',
    'liberia, costa rica': 'the local economy is heavily tied to the surrounding cattle ranching industry',
    'likasi': 'a specialized museum displays an extensive collection of local minerals',
    'loja': 'the local culture is deeply intertwined with traditional music and arts',
    'lubumbashi': 'the local economy relies heavily on intensive copper and cobalt extraction',
    'lucknow': 'the local culture is highly famous for intricate traditional embroidery',
    'luganville': 'a sunken troopship serves as a highly popular recreational dive site',
    'machakos': 'a local park features a gravity-defying optical illusion on a nearby hill',
    'machala': 'the local economy is overwhelmingly dominated by the banana export industry',
    'madurai': 'a massive temple complex features incredibly ornate, brightly colored towers',
    'maiduguri': 'a prominent university here is highly active in arid agriculture research',
    'majuro': 'a highly localized currency is uniquely constructed from woven shells',
    'makassar': 'traditional wooden sailing vessels are highly associated with the local culture',
    'makhachkala': 'the local football club gained international attention after significant financial investment',
    'malacca': 'distinctive red-painted historical buildings reflect colonial architectural influences',
    'malindi': 'a coral pillar commemorates a visit by a famous historical navigator',
    'manado': 'a massive flying statue overlooks the urban grid',
    'manaus': 'an incredibly ornate opera house was constructed during a massive rubber boom',
    'mandalay': 'a massive reconstructed wooden palace complex dominates the central grid',
    'manta': 'the local fishing fleet is a major contributor to the economy',
    'maraba': 'the local economy relies heavily on intensive copper mining',
    'mary': 'the ruins of ancient Merv sit just outside the modern urban grid',
    'matadi': 'a massive suspension bridge provides a crucial transport link',
    'mawlamyine': 'a prominent ridge is lined with numerous golden pagodas',
    'mayaguez': 'a local university focuses heavily on agricultural and engineering research',
    'mbandaka': 'a major botanical garden was established here over a century ago',
    'mbeya': 'a prominent local meteorite is displayed as a significant geological attraction',
    'mbuji-mayi': 'industrial diamond mining sustains the overwhelming majority of the workforce',
    'mecca': 'the focal point of the settlement is a massive cube-shaped structure',
    'medan': 'a massive palace features unique yellow and green architectural details',
    'medina': 'a massive mosque features striking green architectural elements',
    'melekeok': 'a massive stone monolith complex remains an unsolved archaeological mystery',
    'mendoza': 'an extensive network of irrigation canals supports massive local vineyards',
    'meru': 'the local agricultural economy is heavily dependent on the cultivation of miraa',
    'miri': 'the local petroleum industry began with a historic wooden oil well',
    'mombasa': 'narrow streets and carved wooden doors define the historic old town',
    'monywa': 'a towering standing Buddha statue dominates the surrounding plains',
    'morogoro': 'an agricultural university focuses on improving local crop yields',
    'moshi': 'coffee auctions are a crucial component of the local commercial sector',
    'multan': 'highly elaborate shrines are decorated with intricate blue and white tiles',
    'mwanza': 'massive, precariously balanced granite boulders dot the local landscape',
    'naga city': 'a massive annual religious procession draws millions of participants',
    'nagpur': 'the local agricultural economy is heavily focused on intense orange cultivation',
    'najaf': 'a sprawling cemetery here accommodates millions of traditional burials',
    'nakhchivan': 'an intricate mausoleum decorated with turquoise tiles is a major architectural site',
    'nakhon ratchasima': 'a prominent statue commemorates a local heroine who saved the settlement',
    'nakuru': 'the local lake is periodically covered entirely by flocks of pink flamingos',
    'namangan': 'the local economy historically centered on traditional textile and clothing manufacturing',
    'naryn': 'the settlement serves as a major staging point for expeditions into the high mountains',
    'nassau': 'a massive staircase was carved directly out of solid limestone by hand',
    'naypyidaw': 'massive multi-lane highways frequently experience virtually no vehicle traffic',
    'neuquen': 'the local economy is heavily driven by petroleum extraction and fruit cultivation',
    'noumea': 'an aquarium specializes in displaying highly fluorescent local corals',
    'novosibirsk': 'the trans-Siberian railway bridge sparked rapid industrialization here',
    "nuku'alofa": 'free-roaming pigs are a common sight on the streets',
    'nukus': 'an isolated art museum holds a vast collection of avant-garde masterpieces',
    'nyeri': 'the founder of the scouting movement is buried in a local cemetery',
    'ogbomosho': 'the settlement is famous for its historical production of mangoes',
    'omsk': 'the writer Fyodor Dostoevsky spent four years in exile at a local prison camp',
    'onitsha': 'a massive bridge facilitates intensive commercial traffic across the river',
    'oruro': 'a massive annual carnival features intensely elaborate devil masks',
    'osh': 'a prominent sacred rock formation dominates the center of the urban grid',
    'pago pago': 'tuna canning forms the absolute foundation of the local economy',
    'palembang': 'a massive bridge features a distinctive red central tower',
    'palikir': 'the government complex features architecture mimicking traditional meeting houses',
    'palmas': 'the settlement was entirely planned and built specifically to serve as a new administrative center',
    'papeete': 'a bustling municipal market is a primary hub for black pearls',
    'pathein': 'hand-painted umbrellas are a highly famous local handicraft',
    'patna': 'an ancient granary structure was designed to resemble a massive beehive',
    'pattaya': 'a massive wooden sanctuary is continually under construction without metal nails',
    'pavlodar': 'a massive tractor factory was a cornerstone of the Soviet-era economy',
    'penang': 'street art murals interact directly with the physical architecture',
    'peshawar': 'a historic market was long a primary hub for storytellers and merchants',
    'piura': 'the local economy relies heavily on intensive cotton and lemon cultivation',
    'ponce': 'a highly distinctive firehouse features striking red and black architecture',
    'port harcourt': 'the economy is overwhelmingly dominated by the petroleum refinement industry',
    'port vila': 'an underwater post office allows divers to mail waterproof postcards',
    'port-de-paix': 'the settlement historically served as a major hub for banana exports',
    'porto velho': 'a historic, partially completed railway line serves as a major monument',
    'portoviejo': 'the local culinary scene is heavily praised for its traditional stews',
    'potosi': 'the local economy was historically built on extracting massive amounts of silver',
    'pucallpa': 'the lumber industry forms the absolute foundation of the local economy',
    'puerto plata': 'a cable car provides access to a prominent botanical reserve',
    'puntarenas': 'a popular local dish consists of crushed ice flavored with syrup and powdered milk',
    'quetta': 'the local economy relies heavily on the cultivation of apples and grapes',
    'rawalpindi': 'the settlement serves as the primary headquarters for the national military',
    'rio branco': 'the local economy historically centered on intense rubber extraction',
    'riobamba': 'the settlement serves as a major hub for expeditions to a massive nearby volcano',
    'rosario': 'the settlement is widely recognized as the birthplace of the national flag',
    'rustavi': 'a massive metallurgical plant was established here during the Soviet era',
    'saipan': 'a massive cliff face was the site of a tragic historical event',
    'salta': 'the local architecture features some of the best-preserved colonial buildings in the region',
    'samarkand': 'intricate blue-tiled madrasas frame the monumental Registan square',
    'san ignacio': 'a prominent iguana conservation project operates within the town',
    'san miguel, el salvador': 'a major local festival involves intensely throwing fireballs',
    'san pedro de macoris': 'the settlement is famous for producing highly skilled baseball players',
    'sandakan': 'a major sanctuary is dedicated to rehabilitating orphaned orangutans',
    'santa ana, el salvador': 'a highly ornate Gothic-style cathedral dominates the central square',
    'santa clara': 'a massive monument is dedicated to a highly famous revolutionary figure',
    'santa cruz de la sierra': 'the urban layout consists of a series of concentric circular ring roads',
    'santarem': 'a popular local beach features perfectly white sand',
    'santiago de cuba': 'the local culture is deeply intertwined with traditional son music',
    'santiago de los caballeros': 'the local economy relies heavily on tobacco processing and rum production',
    'santo domingo, ecuador': 'the local indigenous culture is highly famous for unique traditional hairstyles',
    'semey': 'the town was a frequent place of exile for nineteenth-century writers',
    'sharjah': 'the local government places a highly intense focus on preserving traditional arts and culture',
    'shymkent': 'a major lead-smelting plant operated heavily during the mid-twentieth century',
    'sibu': 'the annual base jumping festival utilizes the tallest building in town',
    'sittwe': 'a major deepwater facility facilitates intense international trade',
    'srinagar': 'intricately carved wooden houseboats are a highly popular local accommodation',
    'sucre': 'historic buildings are strictly required to be painted entirely white',
    'sulaymaniyah': 'the local culture places a highly intense focus on poetry and literature',
    'sumqayit': 'a major synthetic rubber and chemical hub developed rapidly in the mid-twentieth century',
    'surat thani': 'the local economy relies heavily on rubber plantations and coconut harvesting',
    'tabora': 'mango trees planted by historical caravan traders line the streets',
    'tabuk': 'a historic railway station serves as a major monument to early 20th-century transport',
    'takoradi': 'a deep artificial harbor facilitates the export of cocoa and timber',
    'talas': 'a legendary battle here stopped the expansion of the Arab Caliphates',
    'tamale': 'round traditional huts with conical thatched roofs blend with modern concrete structures',
    'tanga': 'sisal production was historically the primary driver of the local economy',
    'tarawa': 'relics of a massive historical battle are highly visible at low tide',
    'taraz': 'excavations reveal a history of Silk Road merchant activity',
    'tarija': 'the local economy relies heavily on high-altitude wine production',
    'taunggyi': 'a massive hot air balloon festival takes place annually',
    'tel aviv': 'the urban grid features an incredibly high concentration of Bauhaus architecture',
    'thiruvananthapuram': 'a highly ornate temple is rumored to hold massive hidden treasures',
    'timisoara': 'the settlement was the very first in Europe to install electric street lighting',
    'tomsk': 'a large student population attends the oldest university in this part of the continent',
    'trinidad, bolivia': 'the settlement is frequently subject to severe seasonal flooding',
    'trujillo, peru': 'the local culture is intensely tied to a specific style of traditional marinera dance',
    'tshikapa': 'artisanal gem hunting draws many transient workers',
    'tucuman': 'a historic house here was the site of the national declaration of independence',
    'türkmenabat': 'a major nature reserve protects local riparian woodland ecosystems',
    'udon thani': 'a nearby archaeological site revealed ancient bronze age artifacts',
    'ushuaia': 'the local museum is housed in a former high-security prison',
    'uyo': 'a massive modern stadium frequently hosts international football matches',
    'vanadzor': 'chemical production facilities shaped the urban growth during the twentieth century',
    'varanasi': 'a highly intense concentration of stepped ghats leads down to the sacred river',
    'vladikavkaz': 'a Sunni mosque with highly ornate architecture stands as a prominent historical landmark',
    'yakutsk': 'buildings are constructed on concrete stilts driven deep into the permafrost',
    'yaren': 'phosphate mining severely depleted the local environmental resources',
    'yogyakarta': 'traditional batik fabric production is a highly respected local art form',
    'zamboanga city': 'brightly colored traditional sails are a hallmark of local festivals',
    'zaria': 'highly decorated traditional mud-brick gates mark the entrances to the old town',
    'zarqa': 'the local industrial sector relies heavily on a massive petroleum refinery',
})

CITY = dict(NEW)
for _k, _v in _TOPO.items():
    _key = (_k.lower().replace("city of ", "")
                     .replace("city and county of ", "").strip())
    CITY.setdefault(_key, _v)
