"""One identifying clause per place, carrying no hint of any relation.

This is the whole difficulty of the topological corpus. The old one wrote
"The State of California fully envelops the City of Los Angeles", which
answers itself: 'fully envelops' is 'contains', and the reader never needs to
know what either place is. 67% of the old eval items for contains leaked that
way.

So a clause here may not say what a place is inside, next to, or made up of.
Three things are banned outright, because each hands over an answer:

  parentage   "the French capital", "a city in Colorado"  -> contains/within
  neighbours  "on the German border"                      -> touches
  size        "covers 270,000 square kilometres"          -> the area ratio,
                                                             which is exactly
                                                             how difficulty is
                                                             graded

What is left is history, culture, economy and physical character -- enough to
identify the place to a reader who knows geography, and useless to one who
does not. That is the point: the item should be answerable only from knowing
where these places actually are.
"""

IDENTITY = {
 # ---- countries ----
 "France": "France established its Fifth Republic in 1958",
 "Germany": "Germany reunified its two post-war states in 1990",
 "Spain": "Spain returned to constitutional monarchy after 1975",
 "Portugal": "Portugal's Carnation Revolution ended a long dictatorship in 1974",
 "Italy": "Italy completed its unification in 1871",
 "Switzerland": "Switzerland has stayed out of military alliances for centuries",
 "Austria": "Austria declared permanent neutrality in 1955",
 "Belgium": "Belgium runs its affairs in three official languages",
 "Netherlands": "the Netherlands reclaimed much of its farmland from water",
 "Poland": "Poland regained statehood in 1918 after more than a century",
 "Czechia": "Czechia separated from Slovakia peacefully in 1993",
 "Hungary": "Hungary speaks a language unrelated to those around it",
 "Romania": "Romania speaks a Romance language with Slavic borrowings",
 "Greece": "Greece won independence from Ottoman rule in the 1820s",
 "Norway": "Norway's sovereign wealth fund is the largest of its kind",
 "Sweden": "Sweden abandoned two centuries of neutrality in 2024",
 "Finland": "Finland was a grand duchy under Russian rule until 1917",
 "Denmark": "Denmark has one of the oldest continuous monarchies anywhere",
 "Ireland": "Ireland became a republic in 1949",
 "United Kingdom": "the United Kingdom left the European Union in 2020",
 "Morocco": "Morocco has been ruled by the Alaouite dynasty since the 1600s",
 "Algeria": "Algeria won independence after a war lasting until 1962",
 "Tunisia": "Tunisia's uprising in 2010 set off a wider wave of revolts",
 "Libya": "Libya derives almost all its export earnings from oil",
 "Egypt": "Egypt nationalised its great shipping canal in 1956",
 "Sudan": "Sudan lost a third of its territory to secession in 2011",
 "Ethiopia": "Ethiopia was never formally colonised",
 "Kenya": "Kenya's long-distance runners dominate the sport",
 "Tanzania": "Tanzania was formed by a union of two states in 1964",
 "Uganda": "Uganda takes its name from a precolonial kingdom",
 "Nigeria": "Nigeria has the largest population on its continent",
 "Ghana": "Ghana was the first colony south of the Sahara to gain independence",
 "Senegal": "Senegal has never experienced a military coup",
 "Mali": "Mali's medieval empire controlled the trans-Saharan gold trade",
 "Niger": "Niger supplies a significant share of the world's uranium",
 "Chad": "Chad is named after a lake that has shrunk drastically",
 "South Africa": "South Africa holds elections under a constitution adopted in 1996",
 "Namibia": "Namibia was administered by its southern neighbour until 1990",
 "Botswana": "Botswana built its economy on diamond revenue",
 "Zimbabwe": "Zimbabwe abandoned its own currency after hyperinflation",
 "Mozambique": "Mozambique gained independence from Portugal in 1975",
 "Angola": "Angola endured a civil war lasting nearly three decades",
 "Lesotho": "Lesotho lies entirely above one thousand metres",
 "Eswatini": "Eswatini changed its official name from Swaziland in 2018",
 "Brazil": "Brazil moved its seat of government to a purpose-built city in 1960",
 "Argentina": "Argentina absorbed vast Italian and Spanish migration",
 "Chile": "Chile stretches more than four thousand kilometres end to end",
 "Peru": "Peru was the centre of Spanish rule in its region",
 "Bolivia": "Bolivia recognises more than thirty official languages",
 "Ecuador": "Ecuador adopted the US dollar as its currency in 2000",
 "Colombia": "Colombia signed a peace deal with its largest guerrilla group in 2016",
 "Venezuela": "Venezuela holds the largest proven oil reserves in the world",
 "Uruguay": "Uruguay legalised cannabis nationally in 2013",
 "Paraguay": "Paraguay generates nearly all its electricity from hydropower",
 "Mexico": "Mexico's revolution began in 1910 and reshaped its politics",
 "Guatemala": "Guatemala has the largest indigenous population share in its region",
 "Panama": "Panama took full control of its interoceanic waterway in 1999",
 "Canada": "Canada patriated its constitution in 1982",
 "United States": "the United States ratified its constitution in 1788",
 "China": "China opened its economy under reforms begun in 1978",
 "India": "India has more official languages than any comparable state",
 "Nepal": "Nepal abolished its monarchy in 2008",
 "Bhutan": "Bhutan measures progress with a happiness index",
 "Bangladesh": "Bangladesh became independent after a war in 1971",
 "Pakistan": "Pakistan was created by partition in 1947",
 "Afghanistan": "Afghanistan has been called the graveyard of empires",
 "Iran": "Iran's revolution replaced its monarchy in 1979",
 "Iraq": "Iraq holds the ruins of some of the earliest cities",
 "Turkey": "Turkey abolished its caliphate in 1924",
 "Syria": "Syria's uprising in 2011 became a prolonged civil war",
 "Jordan": "Jordan has been ruled by the Hashemite family since its founding",
 "Saudi Arabia": "Saudi Arabia was unified under one dynasty in 1932",
 "Oman": "Oman once controlled trading posts as far as Zanzibar",
 "Yemen": "Yemen unified its northern and southern states in 1990",
 "Japan": "Japan's constitution renounces war as a sovereign right",
 "Vietnam": "Vietnam reunified after 1975",
 "Laos": "Laos is the only landlocked state in its immediate region",
 "Cambodia": "Cambodia's Angkor complex is the largest religious monument anywhere",
 "Thailand": "Thailand avoided formal European colonisation",
 "Malaysia": "Malaysia rotates its monarchy among nine royal houses",
 "Indonesia": "Indonesia spans more than seventeen thousand islands",
 "Australia": "Australia federated its colonies in 1901",
 "New Zealand": "New Zealand granted women the vote in 1893",
 "San Marino": "San Marino claims to be the oldest surviving republic",
 "Vatican City": "Vatican City is the smallest sovereign state in the world",
 "Monaco": "Monaco has been ruled by the Grimaldi family since the 1200s",
 "Andorra": "Andorra has two heads of state serving jointly",
 "Luxembourg": "Luxembourg is the only remaining sovereign grand duchy",
 "Slovenia": "Slovenia was the first republic to leave the Yugoslav federation",
 "Croatia": "Croatia adopted the euro in 2023",
 "Serbia": "Serbia's capital has been destroyed and rebuilt many times over",
 "Bulgaria": "Bulgaria uses the Cyrillic alphabet it helped develop",
}

# ---- US states ----
IDENTITY.update({
 "State of California": "California's economy would rank among the largest national ones",
 "State of Texas": "Texas was an independent republic for nine years",
 "State of Florida": "Florida was transferred from Spanish rule in 1821",
 "State of New York": "New York's harbour received the bulk of transatlantic migration",
 "State of Colorado": "Colorado takes its name from a Spanish word for red",
 "State of Arizona": "Arizona was the last of the contiguous states admitted",
 "State of Nevada": "Nevada legalised casino gambling in 1931",
 "State of Utah": "Utah was settled by members of a religious migration in 1847",
 "State of Oregon": "Oregon has banned self-service fuel for most of its history",
 "State of Washington": "Washington is named after the first US president",
 "State of Alaska": "Alaska was purchased from Russia in 1867",
 "State of Hawaii": "Hawaii was an independent kingdom until 1893",
 "State of Illinois": "Illinois gave the world the steel-framed skyscraper",
 "State of Ohio": "Ohio has produced more US presidents than almost any other state",
 "State of Michigan": "Michigan built the assembly-line motor industry",
 "State of Georgia": "Georgia was the last of the original thirteen colonies founded",
 "State of Virginia": "Virginia hosted the first permanent English settlement in America",
 "State of Maine": "Maine separated from Massachusetts in 1820",
 "State of Montana": "Montana is nicknamed for its wide skies",
 "State of Wyoming": "Wyoming was the first territory to grant women the vote",
 "State of Kansas": "Kansas was the flashpoint of a violent pre-war dispute over slavery",
 "State of Missouri": "Missouri was the starting point for the westward trails",
 "State of Louisiana": "Louisiana keeps a legal code descended from French civil law",
 "State of Alabama": "Alabama was where the bus boycott of 1955 began",
 "State of Pennsylvania": "Pennsylvania was founded as a haven for Quakers",
 "State of Massachusetts": "Massachusetts founded the oldest university in the country",
 "State of Minnesota": "Minnesota advertises itself by its many thousands of lakes",
 "State of New Mexico": "New Mexico was where the first atomic device was detonated",
 "State of Idaho": "Idaho grows a large share of the country's potatoes",
 "State of Nebraska": "Nebraska has the only unicameral state legislature",
})

# ---- cities ----
IDENTITY.update({
 "City of Paris": "Paris hosted the Exposition Universelle of 1900",
 "City of Berlin": "Berlin spent four decades divided by a wall",
 "City of Madrid": "Madrid holds the Prado collection",
 "City of Lisbon": "Lisbon was levelled by an earthquake in 1755",
 "City of Rome": "Rome was founded, by tradition, in 753 BC",
 "City of Vienna": "Vienna was the seat of the Habsburgs for centuries",
 "City of Prague": "Prague's astronomical clock has run since 1410",
 "City of Warsaw": "Warsaw was rebuilt from paintings after 1945",
 "City of Budapest": "Budapest was formed by merging three towns in 1873",
 "City of Athens": "Athens gave democracy its name",
 "City of Oslo": "Oslo awards the peace prize each December",
 "City of Stockholm": "Stockholm is built across fourteen islands",
 "City of Helsinki": "Helsinki was rebuilt in neoclassical style in the 1800s",
 "City of Copenhagen": "Copenhagen has more bicycles than residents",
 "City of Dublin": "Dublin was founded as a Viking trading settlement",
 "City of Amsterdam": "Amsterdam rests on millions of wooden piles",
 "City of Brussels": "Brussels hosts the headquarters of a military alliance",
 "City of Zurich": "Zurich is a centre of private banking",
 "City of Munich": "Munich holds a beer festival drawing six million visitors",
 "City of Milan": "Milan is a global centre of fashion",
 "City of Naples": "Naples has one of the largest historic centres in Europe",
 "City of Venice": "Venice is built on a lagoon of small islands",
 "City of Barcelona": "Barcelona has an unfinished basilica begun in 1882",
 "City of Lyon": "Lyon was the Roman capital of Gaul",
 "City of Marseille": "Marseille was founded by Greek traders",
 "City of Los Angeles": "Los Angeles built the world's dominant film industry",
 "City of San Francisco": "San Francisco burned after an earthquake in 1906",
 "City of San Diego": "San Diego hosts one of the largest naval bases anywhere",
 "City of Seattle": "Seattle grew rich outfitting the Klondike gold rush",
 "City of Portland": "Portland is known for its rose gardens",
 "City of Denver": "Denver sits exactly a mile above sea level",
 "City of Phoenix": "Phoenix is the hottest large city in the country",
 "City of Houston": "Houston runs mission control for crewed spaceflight",
 "City of Dallas": "Dallas grew as a cotton and railway hub",
 "City of Austin": "Austin brands itself a live music capital",
 "City of Chicago": "Chicago reversed the flow of its river in 1900",
 "City of Boston": "Boston's tea protest of 1773 preceded revolution",
 "City of Philadelphia": "Philadelphia is where the Declaration was signed",
 "City of Miami": "Miami has the largest Cuban-descended population outside Cuba",
 "City of Atlanta": "Atlanta was burned in 1864 and rebuilt",
 "City of Detroit": "Detroit gave its name to a sound of popular music",
 "City of Cleveland": "Cleveland's river once caught fire, spurring clean water law",
 "City of Minneapolis": "Minneapolis milled flour for much of a continent",
 "City of New Orleans": "New Orleans is the birthplace of jazz",
 "City of Las Vegas": "Las Vegas was a railway watering stop before the casinos",
 "City of Toronto": "Toronto is among the most linguistically diverse cities anywhere",
 "City of Montreal": "Montreal hosted the summer games of 1976",
 "City of Vancouver": "Vancouver is hemmed between mountains and the sea",
 "City of Calgary": "Calgary holds an annual rodeo drawing a million visitors",
 "City of Cairo": "Cairo has the largest metropolitan population on its continent",
 "City of Nairobi": "Nairobi was founded as a railway depot in 1899",
 "City of Lagos": "Lagos is the most populous city on its continent",
 "City of Accra": "Accra became a colonial seat of administration in 1877",
 "City of Casablanca": "Casablanca's port was largely built under a protectorate",
 "City of Cape Town": "Cape Town began as a resupply station for passing ships",
 "City of Johannesburg": "Johannesburg grew out of a gold rush in the 1880s",
 "City of Tokyo": "Tokyo anchors the most populous urban region on earth",
 "City of Delhi": "Delhi has served as an imperial seat many times over",
 "City of Mumbai": "Mumbai was assembled from seven islands by reclamation",
 "City of Bangkok": "Bangkok has the longest ceremonial name of any capital",
 "City of Sydney": "Sydney's harbour bridge opened in 1932",
 "City of Melbourne": "Melbourne has topped liveability rankings repeatedly",
})

# ---- counties, boroughs ----
IDENTITY.update({
 "Los Angeles County": "Los Angeles County has more residents than most US states",
 "Cook County": "Cook County runs one of the largest court systems in the country",
 "Harris County": "Harris County is named for an early Texan settler family",
 "Maricopa County": "Maricopa County has been among the fastest growing in the country",
 "San Diego County": "San Diego County stretches from surf beaches to desert",
 "Orange County, California": "Orange County was named for the citrus groves that once covered it",
 "King County, Washington": "King County was renamed in 1986 to honour a civil rights leader",
 "Miami-Dade County": "Miami-Dade County was consolidated under a metropolitan charter in 1957",
 "Clark County, Nevada": "Clark County collects most of its revenue from tourism",
 "Wayne County, Michigan": "Wayne County was organised in 1796, the oldest in its state",
 "Kings County, New York": "Kings County is the most populous county in its state",
 "Queens County, New York": "Queens County was named for a Portuguese-born queen consort",
 "Bronx County, New York": "Bronx County is named after an early Swedish settler",
 "Richmond County, New York": "Richmond County is the least populous of its city's counties",
 "New York County, New York": "New York County is the densest county in the United States",
 "Suffolk County, Massachusetts": "Suffolk County was one of the original counties of 1643",
 "Philadelphia County": "Philadelphia County was created by William Penn in 1682",
 "Marin County": "Marin County is known for its redwood groves",
 "Santa Clara County": "Santa Clara County is the heart of the American technology industry",
 "Borough of Manhattan": "Manhattan was bought from the Lenape according to a disputed account",
 "Borough of Brooklyn": "Brooklyn was an independent city until 1898",
 "Borough of Queens": "Queens hosted two World's Fairs",
 "Borough of Staten Island": "Staten Island is connected to its neighbour by a free ferry",
 "The Bronx": "the Bronx is the birthplace of hip hop",
})

# ---- parks, water, rivers, physical, islands ----
IDENTITY.update({
 "Yellowstone National Park": "Yellowstone was the first national park anywhere, designated in 1872",
 "Yosemite National Park": "Yosemite's granite walls draw climbers from around the world",
 "Grand Canyon National Park": "the Grand Canyon exposes nearly two billion years of rock",
 "Everglades National Park": "the Everglades protect a slow-moving river of grass",
 "Glacier National Park": "Glacier National Park has lost most of the ice it was named for",
 "Death Valley National Park": "Death Valley recorded the highest air temperature ever measured",
 "Banff National Park": "Banff was established around a hot spring in 1885",
 "Kruger National Park": "Kruger was proclaimed a game reserve in 1898",
 "Serengeti National Park": "the Serengeti hosts the largest overland animal migration",
 "Central Park": "Central Park was designed by Olmsted and Vaux in 1858",
 "Hyde Park, London": "Hyde Park has a corner set aside for public speaking",
 "Bois de Boulogne": "the Bois de Boulogne was laid out as a public park under Napoleon III",
 "Lake Michigan": "Lake Michigan is the only one of its chain wholly in one country",
 "Lake Superior": "Lake Superior holds more water than the rest of its chain combined",
 "Lake Huron": "Lake Huron has the longest shoreline of its chain",
 "Lake Erie": "Lake Erie is the shallowest of its chain and warms fastest",
 "Lake Ontario": "Lake Ontario is the last of its chain before the sea",
 "Lake Victoria": "Lake Victoria is the largest tropical lake in the world",
 "Lake Tanganyika": "Lake Tanganyika is the second deepest lake on earth",
 "Lake Baikal": "Lake Baikal holds a fifth of the world's unfrozen fresh water",
 "Loch Ness": "Loch Ness is famous for a creature never shown to exist",
 "Lake Geneva": "Lake Geneva is shaped like a crescent and fed by an Alpine river",
 "Lake Constance": "Lake Constance has no formally agreed division among its shores",
 "Great Salt Lake": "the Great Salt Lake is several times saltier than the ocean",
 "Mediterranean Sea": "the Mediterranean was the highway of classical civilisation",
 "Baltic Sea": "the Baltic is among the least saline seas in the world",
 "Black Sea": "the Black Sea has a lifeless layer below two hundred metres",
 "Red Sea": "the Red Sea is one of the warmest and saltiest seas",
 "Caspian Sea": "the Caspian is the largest lake on earth by surface area",
 "North Sea": "the North Sea has yielded oil and gas since the 1970s",
 "Adriatic Sea": "the Adriatic carried the trade of a maritime republic for centuries",
 "Aegean Sea": "the Aegean is scattered with more than a thousand islands",
 "River Thames": "the Thames froze hard enough for frost fairs in past centuries",
 "Seine": "the Seine was the setting for an Olympic opening ceremony in 2024",
 "Rhine": "the Rhine has been a commercial artery since Roman times",
 "Danube": "the Danube passes more capital cities than any other river",
 "Elbe": "the Elbe was a dividing line during the Cold War",
 "Loire": "the Loire valley is lined with Renaissance chateaux",
 "Rhone": "the Rhone is fed by an Alpine glacier",
 "Po": "the Po drains the most productive agricultural plain of its country",
 "Tagus": "the Tagus is the longest river of its peninsula",
 "Ebro": "the Ebro gave its name to an entire peninsula",
 "Vistula": "the Vistula runs past a rebuilt historic capital",
 "Oder": "the Oder became a political boundary after 1945",
 "Nile": "the Nile was long contested as the world's longest river",
 "Niger River": "the Niger takes a great arc through the Sahel before turning south",
 "Congo River": "the Congo is the deepest river in the world",
 "Zambezi": "the Zambezi plunges over one of the largest waterfalls on earth",
 "Orange River": "the Orange is the longest river of its region",
 "Limpopo": "the Limpopo was called great, grey-green and greasy by Kipling",
 "Mississippi River": "the Mississippi drains most of the American interior",
 "Missouri River": "the Missouri is the longest river on its continent",
 "Colorado River": "the Colorado is so heavily drawn upon it often fails to reach the sea",
 "Rio Grande": "the Rio Grande is known by two different names on its two banks",
 "Columbia River": "the Columbia generates more hydroelectricity than any other on its continent",
 "Amazon River": "the Amazon discharges more water than the next several rivers combined",
 "Parana River": "the Parana feeds one of the largest hydroelectric schemes ever built",
 "Ganges": "the Ganges is venerated as a goddess by millions",
 "Indus": "the Indus gave its name to one of the earliest urban civilisations",
 "Mekong": "the Mekong supports the largest inland fishery in the world",
 "Yangtze": "the Yangtze is dammed by the largest power station ever built",
 "Yellow River": "the Yellow River carries so much silt it has changed course repeatedly",
 "Volga": "the Volga is the longest river in Europe",
 "Euphrates": "the Euphrates watered some of the earliest known cities",
 "Tigris": "the Tigris runs past the ruins of Nineveh",
 "Sahara": "the Sahara is the largest hot desert on earth",
 "Kalahari Desert": "the Kalahari is a sand basin that supports more life than most deserts",
 "Namib Desert": "the Namib is thought to be the oldest desert in the world",
 "Gobi Desert": "the Gobi is a cold desert that freezes in winter",
 "Atacama Desert": "the Atacama has places where rain has never been recorded",
 "Mojave Desert": "the Mojave is defined by the range of the Joshua tree",
 "Sonoran Desert": "the Sonoran is the only place the saguaro cactus grows wild",
 "Amazon Rainforest": "the Amazon rainforest holds roughly a tenth of all known species",
 "Alps": "the Alps were formed by the collision of two continental plates",
 "Pyrenees": "the Pyrenees shelter a tiny sovereign principality",
 "Carpathian Mountains": "the Carpathians hold Europe's largest remaining old-growth forest",
 "Himalayas": "the Himalayas contain every peak above eight thousand metres bar a few",
 "Rocky Mountains": "the Rockies form the continental divide of North America",
 "Ural Mountains": "the Urals are treated as a conventional boundary between two continents",
 "Atlas Mountains": "the Atlas range takes its name from a figure of Greek myth",
 "Scandinavian Mountains": "the Scandinavian range is worn down from once far greater heights",
 "Black Forest": "the Black Forest gave its name to a cherry gateau",
 "Sicily": "Sicily has been ruled in turn by Greeks, Arabs and Normans",
 "Sardinia": "Sardinia is dotted with prehistoric stone towers",
 "Corsica": "Corsica was the birthplace of Napoleon",
 "Crete": "Crete was the seat of the Minoan civilisation",
 "Cyprus": "Cyprus has been partitioned since 1974",
 "Iceland": "Iceland runs almost entirely on geothermal and hydroelectric power",
 "Isle of Man": "the Isle of Man has the oldest continuous parliament in the world",
 "Isle of Wight": "the Isle of Wight hosted a famous rock festival in 1970",
 "Greenland": "Greenland is covered by the second largest ice sheet on earth",
 "Madagascar": "Madagascar's wildlife is overwhelmingly found nowhere else",
 "Tasmania": "Tasmania holds some of the last temperate rainforest",
 "Hokkaido": "Hokkaido was settled comparatively recently by its national majority",
 "Honshu": "Honshu holds the great majority of its country's population",
 "Java": "Java is the most populous island in the world",
 "Borneo": "Borneo is divided among three sovereign states",
 "Long Island": "Long Island is the longest island in the contiguous United States",
 "Manhattan Island": "Manhattan Island is bounded by three tidal waterways",
})

# ---- consolidated city-counties (the 'equals' candidates) ----
IDENTITY.update({
 "City and County of San Francisco": "San Francisco's government merged its city and county functions in 1856",
 "City and County of Denver": "Denver's consolidated government was created by a state amendment in 1902",
 "City and County of Honolulu": "Honolulu's consolidated government covers an entire island",
 "Nashville-Davidson": "Nashville's metropolitan government was among the first of its kind in 1963",
 "Davidson County": "Davidson County was named for a Revolutionary War officer",
 "Marion County, Indiana": "Marion County was named for a general nicknamed the Swamp Fox",
 "Consolidated City of Indianapolis": "Indianapolis merged its administration with the surrounding county in 1970",
 "Jefferson County, Kentucky": "Jefferson County was established in 1780 and named for a future president",
 "Louisville": "Louisville was named in honour of a French king who backed the American revolution",
 "Duval County": "Duval County was named for a territorial governor of Florida",
 "Jacksonville": "Jacksonville consolidated with its county in 1968, creating a vast municipal area",
 "Orleans Parish": "Orleans Parish keeps the French term for a county used nowhere else in the country",
 "Suffolk County, New York": "Suffolk County occupies the eastern end of a long glacial island",
 "San Francisco County": "San Francisco County is the smallest county by area in its state",
 "Denver County, Colorado": "Denver County has boundaries that have been redrawn to take in an airport",
 "Honolulu County": "Honolulu County includes a chain of uninhabited northwestern islets",
 "District of Columbia": "the District of Columbia was ceded by Maryland to host a federal capital",
 "Washington, D.C.": "Washington was laid out by Pierre L'Enfant in 1791",
 "Baltimore City": "Baltimore separated from its surrounding county in 1851",
 "St. Louis City": "St. Louis separated from its surrounding county in 1877, a split still debated",
 "Borough of Brooklyn": "Brooklyn was an independent city until 1898",
 "Kings County, New York": "Kings County is the most populous county in its state",
})

# ---------------------------------------------------------------------------
# Entities whose OSM geometry does not represent what the name means. Items
# built on these would be internally consistent and factually wrong, which is
# worse than having none: the label would agree with my polygon while
# disagreeing with the world.
#
#   Interstates / Route 66  resolve to a signposted fragment, not the route
#   Amazon Rainforest       resolves to a conservation concession in Peru
#   Mainland France/Italy   are not OSM objects; the country includes its islands
#   metropolitan areas      are statistical constructs with no boundary relation
#   plates, ridges, trench  geological features not mapped as usable polygons
UNTRUSTED = {
    "Interstate 10", "Interstate 15", "Interstate 80", "Interstate 90",
    "Route 66", "San Andreas Fault", "Mid-Atlantic Ridge", "Mariana Trench",
    "Pacific Plate", "Amazon Rainforest", "Mainland France", "Mainland Italy",
    "Chicago Metropolitan Area", "New York Metropolitan Area",
    "Greater London Built-up Area", "Patagonian Desert", "Sahara Desert",
}

# Ceremonial long forms denote the same object as the short name already
# described, so they reuse its clause rather than inventing a second one.
_ALIAS = {
    "French Republic": "France", "Argentine Republic": "Argentina",
    "Kingdom of Sweden": "Sweden", "Kingdom of Norway": "Norway",
    "Kingdom of Denmark": "Denmark", "Kingdom of Spain": "Spain",
    "Kingdom of Cambodia": "Cambodia", "Federal Republic of Germany": "Germany",
    "Republic of Poland": "Poland", "Republic of Finland": "Finland",
    "Republic of Bulgaria": "Bulgaria", "Republic of Austria": "Austria",
    "Republic of Chile": "Chile", "Republic of Peru": "Peru",
    "Republic of Colombia": "Colombia", "Republic of Ecuador": "Ecuador",
    "Republic of Paraguay": "Paraguay", "Republic of Mali": "Mali",
    "Republic of Chad": "Chad", "Republic of Iraq": "Iraq",
    "Republic of Namibia": "Namibia",
    "Plurinational State of Bolivia": "Bolivia",
}
for _long, _short in _ALIAS.items():
    if _short in IDENTITY:
        IDENTITY[_long] = IDENTITY[_short]

IDENTITY.update({
 "City of Kyoto": "Kyoto was the imperial seat of Japan for over a thousand years",
 "Great Britain": "Great Britain is the largest island in Europe",
 "Republic of Korea": "the Republic of Korea rebuilt itself into an industrial economy after 1953",
 "City of Berkeley": "Berkeley hosts the oldest campus of California's public university system",
 "City of Oakland": "Oakland operates one of the busiest container ports on its coast",
 "City of Somerville": "Somerville is among the most densely settled municipalities in New England",
 "City of Cambridge": "Cambridge houses two of the most heavily endowed universities in the world",
 "City of Palo Alto": "Palo Alto is widely regarded as the birthplace of Silicon Valley",
 "City of Cupertino": "Cupertino is home to a headquarters building shaped like a ring",
 "City of Redmond": "Redmond grew around a software company founded in 1975",
 "City of Bellevue": "Bellevue transformed from a commuter suburb into a corporate centre",
 "City of San Jose": "San Jose was California's first incorporated municipality",
 "City of Eugene": "Eugene is known for distance running and its timber history",
 "City of Provo": "Provo sits beneath the Wasatch Front and hosts a large private university",
 "City of Boise": "Boise is built around a riverside greenbelt trail system",
 "City of Spokane": "Spokane hosted a world's fair in 1974",
 "City of Tempe": "Tempe created a recreational lake from a dammed riverbed",
 "City of Mesa": "Mesa grew rapidly through the late twentieth century",
 "City of Tucson": "Tucson is ringed by stands of saguaro cactus",
 "City of Fort Worth": "Fort Worth preserves a historic livestock exchange district",
 "City of Edina": "Edina opened one of the first indoor shopping malls in the country",
 "City of Lexington": "Lexington calls itself the horse capital of the world",
 "City of Louisville": "Louisville hosts an annual thoroughbred race run since 1875",
 "City of Indianapolis": "Indianapolis holds a motor race staged since 1911",
 "City of Columbus": "Columbus sits on the fall line of the Chattahoochee",
 "City of Augusta": "Augusta hosts an invitational golf tournament each spring",
 "City of Macon": "Macon has a deep history in southern rock and soul music",
 "City of Baton Rouge": "Baton Rouge anchors a large petrochemical corridor",
 "City of Lafayette": "Lafayette is the cultural centre of Cajun country",
 "Fayette County": "Fayette County was named for a French general who served in the American revolution",
 "Jefferson County": "Jefferson County was established in 1780 and named for a future president",
 "Marion County": "Marion County was named for a commander nicknamed the Swamp Fox",
 "King County": "King County was renamed in 1986 to honour a civil rights leader",
 "Clarke County": "Clarke County was created in 1801 and is among the smallest in its state",
 "Bibb County": "Bibb County was named for a physician who became a state governor",
 "Richmond County": "Richmond County was one of the original counties created in 1777",
 "Muscogee County": "Muscogee County takes its name from a confederacy of indigenous nations",
 "Lafayette Parish": "Lafayette Parish was carved out of a neighbouring parish in 1823",
 "East Baton Rouge Parish": "East Baton Rouge Parish is the most populous parish in its state",
 "Tarrant County": "Tarrant County was named for a militia general and formed in 1849",
 "Pima County": "Pima County takes its name from an indigenous people of the Sonoran desert",
 "Teton County": "Teton County has the highest average income of any county in the country",
 "Mariposa County": "Mariposa County was one of California's original twenty-seven counties",
 "State of Indiana": "Indiana calls itself the crossroads of America",
 "State of New Jersey": "New Jersey is the most densely populated state in the country",
 "State of Oklahoma": "Oklahoma was opened to settlers in a series of land runs",
 "State of Tennessee": "Tennessee is closely identified with country music",
 "State of West Virginia": "West Virginia separated from its parent state during the civil war",
 "State of North Dakota": "North Dakota was transformed by shale oil extraction",
 "State of South Dakota": "South Dakota holds a mountainside carved with four presidential faces",
 "State of Hesse": "Hesse is home to the financial centre of Frankfurt",
 "State of Tyrol": "Tyrol is known for alpine skiing and mountaineering",
 "State of Salzburg": "Salzburg was the birthplace of Mozart",
 "Free State of Bavaria": "Bavaria stages an annual festival drawing six million visitors",
 "Canton of Uri": "Uri was one of the three founding members of the Swiss confederation",
 "Canton of Schwyz": "Schwyz gave the Swiss confederation its modern name",
 "Inner Mongolia": "Inner Mongolia is a major source of rare earth minerals",
 "Essex": "Essex is a ceremonial county with a long North Sea coastline",
 "Staten Island": "Staten Island is reached by a free passenger ferry",
 "Nantucket": "Nantucket was once the whaling capital of the world",
 "Mackinac Island": "Mackinac Island bans motor vehicles and preserves 19th-century architecture",
 "Kelleys Island": "Kelleys Island displays deep glacial grooves cut into limestone",
 "Pelee Island": "Pelee Island produces a significant share of its region's wine",
 "Mercer Island": "Mercer Island is reached only by floating pontoon bridges",
 "Grand Island": "Grand Island is known for its sandstone cliffs and forested trails",
 "Antelope Island": "Antelope Island sustains a free-roaming bison herd",
 "Maui": "Maui is dominated by a dormant volcano called Haleakala",
 "Oahu": "Oahu holds the state capital and a historic naval base",
 "Kauai": "Kauai is the oldest major island of its chain and is called the Garden Isle",
 "North Island": "the North Island holds the great majority of New Zealand's population",
 "South Island": "the South Island is renowned for its fjords and glaciers",
 "Lake Washington": "Lake Washington is spanned by floating bridges",
 "Persian Gulf": "the Persian Gulf is ringed by major petroleum production facilities",
 "Gulf of Aden": "the Gulf of Aden is a critical approach to the Bab-el-Mandeb strait",
 "Gulf of Oman": "the Gulf of Oman connects directly to the Arabian Sea",
 "Mekong River": "the Mekong supports the largest inland fishery in the world",
 "Platte River": "the Platte is a critical stopover for migrating sandhill cranes",
 "Arkansas River": "the Arkansas River experiences severe seasonal flow variation",
})

# A few cities appear only in the cardinal catalogue; reuse those clauses so a
# place reads the same wherever it turns up.
try:
    from city_identity import CITY as _CITY
    for _n in list(_CITY):
        # _CITY already absorbed the topological names, so prefixing every key
        # would manufacture entries like "City of Iraq" and "City of France".
        # Only names not already known as places in their own right get one.
        _formal = "City of " + " ".join(w.capitalize() for w in _n.split())
        if _n in IDENTITY or _n.title() in IDENTITY or _formal in IDENTITY:
            continue
        IDENTITY[_formal] = _CITY[_n]
except Exception:
    pass

# Clauses for the ingested topological places, screened the same way.
IDENTITY.update({
    'Acadia National Park': 'the protected landscape is heavily defined by rugged coastal granite and dense pine forests',
    'Aktau': 'the local urban layout utilizes a highly unusual numerical block system instead of street names',
    'Aktobe': 'a highly prominent local planetarium has served as an educational hub for decades',
    'Alabama River': 'the highly dynamic, incredibly historic waterway served as a completely critical, highly navigated transportation route during the intense antebellum era',
    'Alameda County': 'a highly active commercial shipping port facilitates massive international trade',
    'Allegheny County': 'the local economy historically relied almost exclusively on heavy steel manufacturing',
    'Andalusia': 'the regional culture is heavily defined by flamenco music and Moorish architecture',
    'Andijan': 'the settlement is historically significant as the birthplace of a major imperial founder',
    'Apalachicola River': 'the highly dynamic, incredibly pristine waterway supports a completely massive, highly lucrative commercial oyster harvesting industry',
    'Arabian Sea': 'the highly dynamic, incredibly massive water body served as an entirely critical, highly navigated historical trade route',
    'Arches National Park': 'the protected landscape features thousands of naturally occurring sandstone openings',
    'Ardennes': 'the incredibly rugged, highly dense wooded landscape was the completely critical, highly decisive site of a massive twentieth-century military offensive',
    'Atyrau': 'the local architecture features a highly symbolic pedestrian bridge',
    'Baffin Bay': 'the incredibly deep, highly frigid water body is entirely choked by incredibly massive, highly dangerous drifting icebergs',
    'Baffin Island': 'the massive, highly remote landmass supports a very sparse, heavily indigenous population',
    'Balkanabat': 'the local economy was historically founded almost entirely on intense petroleum extraction',
    'Banff National Park': 'the protected area was historically established directly around a series of natural hot springs',
    'Barbados': 'the densely populated landmass historically relied on an incredibly intense sugar cane plantation economy',
    'Barnaul': 'the settlement historically thrived on intense silver smelting before transitioning to agriculture',
    'Basque Country': 'an intense focus on industrial cooperatives heavily influences the regional economy',
    'Batumi': 'the local architecture features highly eclectic contemporary designs and numerous casinos',
    'Bavaria': 'automotive engineering and traditional brewing industries form the core of the economy',
    'Bay of Bengal': 'the incredibly massive, highly dynamic water body experiences incredibly severe, highly destructive seasonal tropical cyclones',
    'Bay of Biscay': 'the highly dynamic, incredibly rugged water body is entirely famous for its incredibly severe, highly unpredictable maritime weather',
    'Benton County': 'the local economy is heavily sustained by the presence of massive corporate retail headquarters',
    'Bexar County': 'a prominent eighteenth-century Spanish mission serves as a major historical landmark',
    'Białowieża Forest': 'the incredibly massive, highly pristine wooded landscape serves as the completely critical, highly protected final refuge for a massive species of wild bison',
    'Biscayne National Park': 'the protected area consists almost entirely of submerged coral reefs and mangrove forests',
    'Bokhtar': 'the local cultural museum features a highly detailed diorama of regional agricultural practices',
    'Bora Bora': 'the highly scenic landmass is heavily reliant on an incredibly intensive luxury resort industry',
    'Brandenburg': 'extensive pine forests and historical aristocratic palaces feature heavily in the landscape',
    'Brazos River': 'the highly dynamic, incredibly expansive waterway served as a completely critical, highly utilized historical focal point for early regional colonial settlement',
    'Brevard County': 'the local economy is intensely tied to federal space exploration and rocket launches',
    'Broward County': 'a massive recreational boating industry defines the local coastal culture and economy',
    'Bryce Canyon National Park': 'the protected area is highly famous for its incredibly dense concentration of eroded rock spires',
    'Bukhara': 'a massive brick minaret is highly famous for surviving numerous historical invasions',
    'Cairngorms National Park': 'the protected landscape features a massive, highly elevated subarctic plateau ecosystem',
    'Canton of Bern': 'the local government strictly enforces heritage preservation for its medieval architecture',
    'Canton of Lucerne': 'tourism relies heavily on the preserved wooden bridges and historic town squares',
    'Canton of Vaud': 'the jurisdiction maintains a highly specialized industry in precision watchmaking',
    'Canton of Zurich': 'global banking and financial services dominate the municipal employment sector',
    'Canyonlands National Park': 'the protected landscape consists of a massive, heavily eroded high desert plateau',
    'Cape Breton Island': 'the landmass is highly famous for its deeply preserved Celtic musical and cultural traditions',
    'Capitol Reef National Park': 'the protected area is defined by a massive, highly visible geological monocline fold',
    'Catalonia': 'a highly distinct regional language heavily influences local political movements',
    'Chattahoochee River': 'the incredibly dynamic, highly engineered waterway provides completely critical, absolutely massive municipal water supplies for a major urban agglomeration',
    'Chiloe Island': 'the landmass is highly famous for its deeply distinct, entirely wooden traditional church architecture',
    'Churchill River': 'the incredibly rugged, highly complex waterway served as a completely critical, highly navigated historic fur trade route',
    'Cobb County': 'the local economy transitioned rapidly from cotton farming to intense suburban commercial retail',
    'Collin County': 'the jurisdiction experienced explosive corporate relocation and rapid residential growth',
    'Contra Costa County': 'a heavy concentration of petroleum refineries drives the local industrial sector',
    'Corfu': 'the lush landmass features highly prominent Venetian architectural and cultural influences',
    'Crater Lake National Park': 'the protected area features an incredibly deep, intensely blue body of water filling a volcanic caldera',
    'Cuba': 'the large landmass experienced a highly significant, globally impactful political revolution in the twentieth century',
    'Cumberland River': 'the highly dynamic, incredibly scenic waterway features a completely massive, highly spectacular natural waterfall along its primary course',
    'Cuyahoga County': 'the local culture is heavily defined by its historical legacy in the rock and roll music industry',
    'Dallas County': 'a massive telecommunications and corporate banking sector drives the commercial landscape',
    'Dartmoor National Park': 'the protected landscape is heavily defined by exposed granite hilltops and wild roaming ponies',
    'Daşoguz': 'the local culture places an incredibly high value on traditional hand-woven textiles',
    'DeKalb County': 'the jurisdiction houses several highly prominent research universities and medical centers',
    'Delaware River': 'the highly dynamic, incredibly historic waterway was the site of a completely critical, highly famous revolutionary military crossing',
    'Denali National Park': 'the protected area is entirely dominated by the absolute highest mountain peak on the continent',
    'Denton County': 'a massive aviation and defense manufacturing sector heavily drives local employment',
    'Derbent': 'ancient stone fortifications constructed by early empires remain a highly prominent feature',
    'Des Moines River': 'the highly dynamic, incredibly complex waterway experienced a completely massive, highly destructive historical flooding event that severely damaged the regional civic center',
    'Dinaric Alps': 'the incredibly rugged, highly complex geological landscape features an absolutely massive, highly extensive network of completely subterranean limestone karst caves',
    'Dry Tortugas National Park': 'the protected landscape features a massive, unfinished nineteenth-century coastal fortress',
    'DuPage County': 'the jurisdiction transitioned from agricultural farmland to a massive commercial research hub',
    'Easter Island': 'the highly isolated landmass features hundreds of massive, incredibly distinct carved stone heads',
    'Ellesmere Island': 'the highly remote, intensely glaciated landmass serves as a critical base for high Arctic research',
    'Erie County, New York': 'the local economy historically thrived on massive grain milling and canal shipping',
    'Fairfax County': 'a massive concentration of government contractors and intelligence firms drives the local workforce',
    'Falkland Islands': 'the highly rugged, wind-swept landmass supports incredibly massive populations of wild penguins',
    'Fergana': 'the urban layout features extremely wide, tree-lined avenues characteristic of military garrisons',
    'Fiordland National Park': 'the protected area features incredibly deep, dramatically carved coastal inlets',
    'Franklin County, Ohio': 'the jurisdiction relies heavily on insurance, banking, and academic research institutions',
    'Fresno County': 'the local economy is overwhelmingly dependent on intensive agricultural production and farming',
    'Fulton County': 'a massive international airport drives incredibly heavy logistics and commercial traffic',
    'Galapagos National Park': 'the protected area is heavily dedicated to preserving incredibly unique, highly specialized endemic wildlife',
    'Galicia': 'the local culinary tradition relies intensely on octopus and fresh seafood',
    'Ganja': 'the local culture heavily honors a famous twelfth-century poet born in the settlement',
    'Gila River': 'the incredibly arid, highly dynamic waterway is completely critical for absolutely massive, highly intensive desert agricultural irrigation',
    'Glacier Bay National Park': 'the protected area features massive, highly active tidewater glaciers dramatically calving into the ocean',
    'Grand Teton National Park': 'the protected landscape features incredibly sharp, dramatically steep mountain peaks',
    'Great Bear Lake': 'the incredibly vast, highly isolated freshwater body is heavily locked in thick ice for most of the year',
    'Great Slave Lake': 'the incredibly deep, highly frigid freshwater body supports a highly active commercial ice fishing industry',
    'Great Smoky Mountains National Park': 'the protected landscape is incredibly famous for its dense, blue-tinted atmospheric haze',
    'Grozny': 'the urban grid underwent massive reconstruction following severe late-twentieth-century conflicts',
    'Gwinnett County': 'a massive commercial retail sector heavily influences the local suburban economy',
    'Gyumri': 'the local architecture is heavily defined by the extensive use of black volcanic tuff stone',
    'Hainan': 'the tropical landmass is heavily promoted as a massive, highly lucrative domestic tourist destination',
    'Hamilton County, Ohio': 'a highly active consumer goods manufacturing sector historically drove the local economy',
    'Hennepin County': 'the local economy is heavily driven by medical device manufacturing and corporate retail',
    'Hillsborough County': 'a prominent cigar manufacturing industry historically defined the early economic growth',
    'Hispaniola': 'the incredibly diverse landmass experienced a highly complex, deeply divided colonial political history',
    'Hudson River': 'the highly scenic, incredibly historic waterway is completely flanked by incredibly massive, highly steep basalt cliffs',
    'Illinois River': 'the highly engineered, incredibly dynamic waterway serves as a completely critical, highly navigated commercial shipping link between two massive aquatic basins',
    'Irkutsk': 'the historic district is heavily defined by highly ornate traditional wooden architecture',
    'Jalal-Abad': 'the local economy benefits significantly from popular natural thermal mineral springs',
    'Jamaica': 'the tropical landmass originated a highly influential, globally recognized style of popular music',
    'James River': 'the highly historic, incredibly dynamic waterway served as the completely critical, highly navigated lifeline for an incredibly famous early colonial settlement',
    'Jasper National Park': 'the protected landscape features massive, highly accessible glacial ice fields',
    'Joshua Tree National Park': 'the protected landscape is famous for its highly distinct, twisting desert vegetation',
    'Karakol': 'a highly distinctive local church was constructed from wood entirely without the use of metal nails',
    'Khabarovsk': 'the local culture features a massive annual festival dedicated to elaborate ice sculptures',
    'Khiva': 'the historic inner town is intensely preserved and protected by massive mud-brick walls',
    'Khorugh': 'a highly specialized botanical garden cultivates plants adapted to extreme environments',
    'Khujand': 'a massive historical fortress serves as a highly prominent feature of the local landscape',
    'Kings Canyon National Park': 'the protected landscape features incredibly deep, dramatically carved glacial valleys',
    'Kodiak Island': 'the rugged landmass is heavily populated by an incredibly massive, highly distinct subspecies of brown bear',
    'Kokshetau': 'the local industrial sector relies heavily on intensive dairy and grain processing',
    'Kootenay National Park': 'the protected landscape features highly distinct natural thermal mineral springs',
    'Krasnoyarsk': 'a massive hydroelectric dam prominently features in the local industrial landscape',
    'Kulob': 'a massive mausoleum honors a highly prominent historical poet and scholar',
    'Kutaisi': 'a massive restored medieval cathedral stands as a highly prominent local landmark',
    'Kyzylorda': 'a highly prominent local dam was constructed specifically to manage extreme seasonal flooding',
    'Lake Albert': 'the massive, highly remote freshwater body serves as a completely critical, highly productive local commercial fishery',
    'Lake Athabasca': 'the large, highly remote freshwater body is heavily impacted by nearby massive oil sands extraction',
    'Lake Chad': 'the incredibly shallow, highly dynamic water body experienced a massively severe, highly disruptive historical reduction in volume',
    'Lake Champlain': 'the elongated freshwater body was the site of a highly significant, incredibly decisive historical naval battle',
    'Lake District National Park': 'the protected landscape heavily inspired a prominent movement of nineteenth-century romantic poets',
    'Lake Kivu': 'the incredibly deep, highly dynamic freshwater body contains an incredibly massive, highly dangerous concentration of dissolved methane gas',
    'Lake Ladoga': 'the incredibly massive, highly deep freshwater body served as a completely critical winter supply route during a historic siege',
    'Lake Malawi': 'the incredibly deep, highly dynamic freshwater body supports an incredibly massive diversity of specialized cichlid fish',
    'Lake Maracaibo': 'the massive, highly unique water body experiences incredibly intense, highly frequent atmospheric lightning storms',
    'Lake Mead': 'the massive, highly critical artificial reservoir provides municipal water for incredibly massive desert cities',
    'Lake Nicaragua': 'the massive, highly dynamic freshwater body supports an incredibly unique, highly adapted population of freshwater sharks',
    'Lake Nipigon': 'the massive, highly pristine freshwater body is deeply revered by local indigenous populations',
    'Lake Okeechobee': 'the highly shallow, incredibly expansive freshwater body is heavily constrained by massive artificial flood dikes',
    'Lake Onega': 'the massive, highly complex freshwater body features an incredibly famous, heavily preserved traditional wooden church complex',
    'Lake Peipus': 'the massive, highly frigid freshwater body was the site of an incredibly famous, highly decisive medieval ice battle',
    'Lake Poopo': 'the incredibly shallow, highly saline water body is entirely prone to complete, highly destructive evaporation events',
    'Lake Powell': 'the massive, entirely artificial freshwater body experiences incredibly severe, highly visible fluctuating water levels',
    'Lake Tahoe': 'the incredibly clear, highly elevated freshwater body is heavily surrounded by massive luxury ski resorts',
    'Lake Tana': 'the highly elevated, incredibly dynamic freshwater body serves as the absolute primary source for a massive continental river',
    'Lake Titicaca': 'the incredibly elevated, highly massive freshwater body features uniquely constructed, entirely floating reed islands',
    'Lake Turkana': 'the incredibly massive, highly alkaline water body is entirely surrounded by an incredibly harsh, heavily arid desert environment',
    'Lake Winnebago': 'the highly shallow freshwater body supports an incredibly massive, highly regulated seasonal sturgeon spearing industry',
    'Lake Winnipeg': 'the massive, highly shallow freshwater body experiences incredibly severe, highly destructive summer algae blooms',
    'Lake of the Woods': 'the highly complex freshwater body features an incredibly massive number of small, heavily forested islands',
    'Lee County, Florida': 'the jurisdiction historically served as a prominent winter retreat for famous inventors',
    'Loch Lomond': 'the elongated, highly scenic freshwater body is deeply celebrated in highly traditional regional folk music',
    'Lough Corrib': 'the complex, highly scenic freshwater body features hundreds of incredibly small, highly distinctive rocky islands',
    'Lough Neagh': 'the massive, highly shallow freshwater body supports an incredibly significant, highly lucrative commercial eel fishery',
    'Luzon': 'the incredibly populous landmass serves as the absolute political and economic engine of the archipelago',
    'Mackenzie River': 'the incredibly massive, highly remote waterway drains an incredibly vast, entirely pristine northern wilderness basin',
    'Macomb County': 'the jurisdiction features a highly affluent residential base tied to the automotive industry',
    'Makhachkala': 'the local sporting culture received massive financial investments in the early twenty-first century',
    'Maldives': 'the highly dispersed landmass relies entirely on an incredibly intensive, highly exclusive luxury tourism sector',
    'Mauritius': 'the highly diverse landmass was the only known historical habitat of a famous, highly extinct flightless bird',
    'Mecklenburg County': 'the jurisdiction serves as a massive national hub for corporate banking and finance',
    'Mesa Verde National Park': 'the protected landscape is highly famous for incredibly well-preserved ancient cliff dwellings',
    'Middlesex County, Massachusetts': 'the local culture is intensely shaped by centuries of academic and historical preservation',
    'Milwaukee County': 'a massive historical brewing industry heavily defined the local culture and architecture',
    'Mindanao': 'the large, highly diverse landmass features a highly complex, deeply divided religious demographic history',
    'Minnesota River': 'the highly dynamic, incredibly complex waterway flows entirely through a completely massive, highly productive agricultural valley',
    'Mobile River': 'the highly dynamic, incredibly deep waterway serves as a completely critical, highly navigated commercial shipping artery to a massive maritime port',
    'Montgomery County': 'biotechnology research and federal medical institutions dominate the employment sector',
    'Mount Rainier National Park': 'the protected landscape is entirely dominated by a massive, heavily glaciated stratovolcano',
    'Nakhchivan': 'an intricately tiled historic mausoleum serves as a highly prominent architectural site',
    'Namangan': 'the local economy historically focused almost entirely on traditional textile weaving',
    'Naryn': 'the settlement serves as a major logistical hub for high-altitude mountain expeditions',
    'Nassau County': 'the jurisdiction was a primary site for early twentieth-century mass suburban development',
    'Nelson River': 'the highly dynamic, incredibly powerful waterway is entirely critical for massive, highly lucrative regional hydroelectric power generation',
    'New Caledonia': 'the landmass relies incredibly heavily on a massive, highly lucrative nickel mining industry',
    'New Forest': 'the incredibly historic, highly protected wooded landscape was completely officially designated as an absolutely massive, highly exclusive royal hunting ground centuries ago',
    'New Guinea': 'the massive, incredibly rugged landmass features highly impenetrable, completely unmapped highland jungles',
    'Newfoundland': 'the rugged landmass historically relied almost entirely on an incredibly intense cod fishing industry',
    'Ngorongoro Conservation Area': 'the protected landscape is entirely contained inside a massive, intact volcanic caldera',
    'North Rhine-Westphalia': 'heavy coal and steel production historically defined the industrial landscape',
    'Northern Ireland': 'the jurisdiction experienced a highly complex political conflict throughout the twentieth century',
    'Northern Territory': 'a massive aboriginal cultural heritage shapes the local societal fabric',
    'Novosibirsk': 'the local economy grew rapidly following the construction of a major transcontinental railway bridge',
    'Nukus': 'a highly remote museum houses a massive collection of preserved avant-garde art',
    'Oakland County': 'the local employment sector relies heavily on automotive engineering and corporate headquarters',
    'Ohio River': 'the incredibly massive, highly dynamic waterway served as the absolutely primary, completely critical historical migration route into the western frontier',
    'Olympic National Park': 'the protected area features an incredibly dense, highly preserved temperate rainforest ecosystem',
    'Omsk': 'the settlement served as a major site of political exile during the nineteenth century',
    'Orange County, Florida': 'the local economy is overwhelmingly dedicated to massive theme parks and hospitality',
    'Osh': 'a massive, highly prominent sacred rock formation dominates the center of the settlement',
    'Palawan': 'the elongated landmass features an incredibly massive, highly complex navigable underground river system',
    'Palm Beach County': 'the local economy caters heavily to wealthy retirees and luxury golf resorts',
    'Pavlodar': 'a massive factory dedicated to producing agricultural tractors historically drove the economy',
    'Peak District National Park': 'the protected area features highly distinct, steep limestone valleys and rugged gritstone moorland',
    'Pecos River': 'the highly dynamic, incredibly remote waterway historically served as a completely critical, highly symbolic boundary for wild frontier lawlessness',
    'Pembrokeshire Coast National Park': 'the protected area is entirely dedicated to preserving an incredibly rugged, highly scenic maritime coastline',
    'Pierce County': 'a massive military installation heavily influences the local employment and economy',
    'Pinellas County': 'the local demographics skew heavily toward retirees drawn by the warm climate',
    'Plitvice Lakes National Park': 'the protected landscape features a highly complex series of cascading travertine waterfalls',
    'Polk County, Florida': 'the local landscape is heavily scarred by intensive historic phosphate mining',
    'Potomac River': 'the incredibly historic, highly dynamic waterway flows entirely directly past an incredibly massive, highly significant array of national monuments',
    "Prince George's County": 'a massive federal aerospace research facility heavily influences local development',
    'Province of British Columbia': 'a massive logging industry relies heavily on dense temperate rainforests',
    'Province of New Brunswick': 'the jurisdiction is officially bilingual with significant Acadian heritage',
    'Province of Nova Scotia': 'the economy historically relied heavily on cod fishing and shipbuilding',
    'Province of Ontario': 'automotive manufacturing and finance heavily drive the local economy',
    'Province of Quebec': 'francophone culture heavily influences the provincial government and daily civic life',
    'Province of Saskatchewan': 'potash mining and massive agricultural plains define the local economy',
    'Puerto Rico': 'the highly populated landmass heavily blends Spanish colonial architecture with modern commercial development',
    'Ramsey County': 'the local economy relies heavily on state government administration and academic institutions',
    'Redwood National Park': 'the protected area is dedicated to preserving the absolutely tallest tree species on the planet',
    'Rhodes': 'the historic landmass was famous in antiquity for a massive, highly celebrated bronze statue',
    'Riverside County': 'the jurisdiction transitioned rapidly from citrus farming to massive residential development',
    'Roanoke River': 'the highly dynamic, incredibly complex waterway is entirely regulated by a completely massive, highly engineered cascade of hydroelectric dams',
    'Rocky Mountain National Park': 'the protected area features incredibly high-altitude alpine tundra and numerous glacial lakes',
    "Rub' al Khali": 'the incredibly vast, highly remote arid landscape is completely devoid of absolutely any permanent, highly established human settlement',
    'Rustavi': 'the settlement was artificially established to support a massive metallurgical complex',
    'Sacramento County': 'the local employment sector is overwhelmingly focused on state bureaucratic administration',
    'Salt Lake County': 'the jurisdiction was founded as a religious sanctuary and features distinct wide municipal grids',
    'Samarkand': 'massive, intensely decorated historic madrasas dominate the primary civic square',
    'Samoa': 'the local culture places an incredibly high value on complex, highly traditional full-body tattooing',
    'San Bernardino County': 'a massive logistics and warehousing industry dominates the local employment sector',
    'San Juan River': 'the highly dynamic, incredibly scenic waterway features entirely massive, highly spectacular entrenched meandering geological canyons',
    'San Mateo County': 'venture capital firms and internet technology campuses densely populate the area',
    'Savannah River': 'the highly dynamic, incredibly scenic waterway was entirely critical for the completely massive, highly lucrative historical export of raw cotton',
    'Saxony': 'the local porcelain industry gained massive international fame over centuries',
    'Scotland': 'a distinct legal and educational system operates independently of its peers',
    'Sea of Azov': 'the incredibly shallow, highly murky water body experiences remarkably severe, highly disruptive winter freezing',
    'Semey': 'the settlement was a frequent destination for prominent exiled intellectuals and writers',
    'Sequoia National Park': 'the protected area preserves groves of incredibly massive, ancient coniferous trees',
    'Seychelles': 'the remote landmass features incredibly unique, highly massive indigenous tortoise species',
    'Shenandoah National Park': 'the protected area features a highly prominent historic scenic driving route',
    'Sherwood Forest': 'the incredibly historic, highly scenic wooded landscape is completely heavily associated with an absolutely massive, highly famous legendary local outlaw',
    'Shymkent': 'a massive lead-smelting operation historically dominated the local industrial output',
    'Simpson Desert': 'the incredibly massive, highly arid landscape features an absolutely massive, highly famous parallel dune system that strictly dictates travel routes',
    'Snohomish County': 'aerospace manufacturing and commercial aviation form the absolute core of the economy',
    'Snowdonia National Park': 'the protected area features an incredibly rugged, highly historic mountainous landscape',
    'Socotra': 'the highly isolated landmass features incredibly unique, highly distinct umbrella-shaped tree species',
    'Solomon Islands': 'the tropical landmass was the site of incredibly intense, highly destructive World War II naval battles',
    'South Georgia': 'the heavily glaciated, highly remote landmass historically served as a major commercial whaling hub',
    'Sri Lanka': 'the teardrop-shaped landmass historically produced an incredibly massive, highly valuable tea export crop',
    'State of South Australia': 'the local climate supports highly renowned viticulture and wine production',
    'State of Victoria': 'a massive gold rush in the mid-nineteenth century drastically accelerated early settlement',
    'State of Western Australia': 'intensive iron ore extraction forms the absolute backbone of the economy',
    'Sulawesi': 'the uniquely shaped landmass features highly distinct, incredibly elaborate traditional funeral ceremonies',
    'Sumatra': 'the massive, highly volcanic landmass supports critically endangered populations of wild orangutans',
    'Sumqayit': 'the settlement developed incredibly rapidly as a hub for synthetic rubber manufacturing',
    'Susquehanna River': 'the highly shallow, incredibly expansive waterway is completely unnavigable for incredibly massive, highly lucrative commercial shipping',
    'Tahiti': 'the tropical landmass serves as the primary administrative and commercial hub for the surrounding archipelago',
    'Taklamakan Desert': 'the incredibly massive, highly arid landscape is completely famous for absolutely massive, highly destructive shifting sand dunes that routinely bury ancient outposts',
    'Talas': 'the local history is deeply tied to a massive legendary battle that shaped regional religion',
    'Taraz': 'extensive local archaeological excavations frequently uncover ancient merchant artifacts',
    'Tarrant County': 'the local culture heavily emphasizes its historical roots in the cattle driving industry',
    'Tennessee River': 'the highly dynamic, incredibly engineered waterway was entirely transformed by a completely massive, highly ambitious federal hydroelectric project',
    'Thar Desert': 'the incredibly vast, highly arid landscape supports an absolutely massive, highly dense population relative to completely typical arid environments',
    'Theodore Roosevelt National Park': 'the protected landscape preserves rugged badlands heavily associated with an early conservationist president',
    'Thuringia': 'a deep literary and philosophical tradition centers on the historic local universities',
    'Tierra del Fuego': 'the incredibly rugged, highly frigid landmass features heavily dramatically carved coastal fjords',
    'Tobago': 'the tropical landmass is heavily reliant on a highly developed international tourism industry',
    'Tombigbee River': 'the highly dynamic, incredibly engineered waterway was entirely modified to create a completely massive, highly navigable commercial shipping canal',
    'Tomsk': 'a highly prominent student population drives the culture of the historic academic center',
    'Torres del Paine National Park': 'the protected landscape features highly distinctive, incredibly sheer granite mountain horns',
    'Travis County': 'the local economy is heavily driven by a massive concentration of technology firms and live music',
    'Trinidad': 'the local culture originated a highly distinct musical style utilizing tuned steel industrial drums',
    'Trinity River': 'the highly dynamic, incredibly engineered waterway provides completely critical, absolutely massive municipal water supplies for a gigantic urban agglomeration',
    'Tuscany': 'the regional landscape is world-famous for its Renaissance art and rolling agricultural estates',
    'Türkmenabat': 'a highly prominent nature reserve protects unique local riparian ecosystems',
    'Vanadzor': 'a massive chemical production industry historically dominated the local employment sector',
    'Vancouver Island': 'the landmass features a highly temperate climate and incredibly dense, ancient coniferous forests',
    'Vanuatu': 'the highly diverse landmass features an incredibly high density of distinct indigenous languages',
    'Victoria Island': 'the enormous, incredibly frigid landmass features absolutely massive herds of migrating caribou',
    'Vladikavkaz': 'a highly ornate historic mosque stands as a prominent architectural landmark',
    'Volusia County': 'the local culture is deeply tied to historical and contemporary stock car racing',
    'Voyageurs National Park': 'the protected landscape is entirely reliant on watercraft for primary transportation and exploration',
    'Wabash River': 'the highly dynamic, incredibly expansive waterway is entirely celebrated as the completely official, highly revered state river of an American jurisdiction',
    'Wake County': 'a massive research triangle drives an intense concentration of pharmaceutical development',
    'Wales': 'the regional identity is deeply tied to choral singing and historical coal mining',
    'Washoe County': 'the local economy is heavily dedicated to casino gaming and transient entertainment',
    'Westchester County': 'the local landscape features numerous preserved Gilded Age aristocratic estates',
    'Wind Cave National Park': 'the protected area features an incredibly dense, highly complex subterranean cavern system',
    'Wisconsin River': 'the highly dynamic, incredibly scenic waterway is completely heavily utilized for incredibly massive, highly popular recreational canoeing and camping',
    'Yakutsk': 'local construction relies entirely on specialized stilts driven deep into the permafrost',
    'Yoho National Park': 'the protected area is highly famous for a massive, incredibly significant fossil discovery site',
    'Yukon River': 'the incredibly long, highly frigid waterway served as a completely critical, highly navigated historic gold rush transportation route',
    'Zanzibar': 'the historic landmass historically served as a massively important hub for the global spice trade',
    'Zion National Park': 'the protected landscape features incredibly massive, vertical red sandstone cliff walls',
})
