"""One identifying clause per place, carrying no hint of any relation.

This is the whole difficulty of the topological corpus. The old one wrote
"The State of California fully envelops the City of Los Angeles", which
answers itself: 'fully envelops' is 'contains', and the reader never needs to
know what either place is. 67% of the old eval items for contains leaked that
way.

So a clause here may not say what a place is inside, next to, or made up of.
Three things are banned outright, because each hands over an answer:

  parentage   "the French capital", "a city in Colorado"  -> contains/within
  neighbours  "on the German border"                      -> touches
  size        "covers 270,000 square kilometres"          -> the area ratio,
                                                             which is exactly
                                                             how difficulty is
                                                             graded

What is left is history, culture, economy and physical character -- enough to
identify the place to a reader who knows geography, and useless to one who
does not. That is the point: the item should be answerable only from knowing
where these places actually are.
"""

IDENTITY = {
 # ---- countries ----
 "France": "France established its Fifth Republic in 1958",
 "Germany": "Germany reunified its two post-war states in 1990",
 "Spain": "Spain returned to constitutional monarchy after 1975",
 "Portugal": "Portugal's Carnation Revolution ended a long dictatorship in 1974",
 "Italy": "Italy completed its unification in 1871",
 "Switzerland": "Switzerland has stayed out of military alliances for centuries",
 "Austria": "Austria declared permanent neutrality in 1955",
 "Belgium": "Belgium runs its affairs in three official languages",
 "Netherlands": "the Netherlands reclaimed much of its farmland from water",
 "Poland": "Poland regained statehood in 1918 after more than a century",
 "Czechia": "Czechia separated from Slovakia peacefully in 1993",
 "Hungary": "Hungary speaks a language unrelated to those around it",
 "Romania": "Romania speaks a Romance language with Slavic borrowings",
 "Greece": "Greece won independence from Ottoman rule in the 1820s",
 "Norway": "Norway's sovereign wealth fund is the largest of its kind",
 "Sweden": "Sweden abandoned two centuries of neutrality in 2024",
 "Finland": "Finland was a grand duchy under Russian rule until 1917",
 "Denmark": "Denmark has one of the oldest continuous monarchies anywhere",
 "Ireland": "Ireland became a republic in 1949",
 "United Kingdom": "the United Kingdom left the European Union in 2020",
 "Morocco": "Morocco has been ruled by the Alaouite dynasty since the 1600s",
 "Algeria": "Algeria won independence after a war lasting until 1962",
 "Tunisia": "Tunisia's uprising in 2010 set off a wider wave of revolts",
 "Libya": "Libya derives almost all its export earnings from oil",
 "Egypt": "Egypt nationalised its great shipping canal in 1956",
 "Sudan": "Sudan lost a third of its territory to secession in 2011",
 "Ethiopia": "Ethiopia was never formally colonised",
 "Kenya": "Kenya's long-distance runners dominate the sport",
 "Tanzania": "Tanzania was formed by a union of two states in 1964",
 "Uganda": "Uganda takes its name from a precolonial kingdom",
 "Nigeria": "Nigeria has the largest population on its continent",
 "Ghana": "Ghana was the first colony south of the Sahara to gain independence",
 "Senegal": "Senegal has never experienced a military coup",
 "Mali": "Mali's medieval empire controlled the trans-Saharan gold trade",
 "Niger": "Niger supplies a significant share of the world's uranium",
 "Chad": "Chad is named after a lake that has shrunk drastically",
 "South Africa": "South Africa holds elections under a constitution adopted in 1996",
 "Namibia": "Namibia was administered by its southern neighbour until 1990",
 "Botswana": "Botswana built its economy on diamond revenue",
 "Zimbabwe": "Zimbabwe abandoned its own currency after hyperinflation",
 "Mozambique": "Mozambique gained independence from Portugal in 1975",
 "Angola": "Angola endured a civil war lasting nearly three decades",
 "Lesotho": "Lesotho lies entirely above one thousand metres",
 "Eswatini": "Eswatini changed its official name from Swaziland in 2018",
 "Brazil": "Brazil moved its seat of government to a purpose-built city in 1960",
 "Argentina": "Argentina absorbed vast Italian and Spanish migration",
 "Chile": "Chile stretches more than four thousand kilometres end to end",
 "Peru": "Peru was the centre of Spanish rule in its region",
 "Bolivia": "Bolivia recognises more than thirty official languages",
 "Ecuador": "Ecuador adopted the US dollar as its currency in 2000",
 "Colombia": "Colombia signed a peace deal with its largest guerrilla group in 2016",
 "Venezuela": "Venezuela holds the largest proven oil reserves in the world",
 "Uruguay": "Uruguay legalised cannabis nationally in 2013",
 "Paraguay": "Paraguay generates nearly all its electricity from hydropower",
 "Mexico": "Mexico's revolution began in 1910 and reshaped its politics",
 "Guatemala": "Guatemala has the largest indigenous population share in its region",
 "Panama": "Panama took full control of its interoceanic waterway in 1999",
 "Canada": "Canada patriated its constitution in 1982",
 "United States": "the United States ratified its constitution in 1788",
 "China": "China opened its economy under reforms begun in 1978",
 "India": "India has more official languages than any comparable state",
 "Nepal": "Nepal abolished its monarchy in 2008",
 "Bhutan": "Bhutan measures progress with a happiness index",
 "Bangladesh": "Bangladesh became independent after a war in 1971",
 "Pakistan": "Pakistan was created by partition in 1947",
 "Afghanistan": "Afghanistan has been called the graveyard of empires",
 "Iran": "Iran's revolution replaced its monarchy in 1979",
 "Iraq": "Iraq holds the ruins of some of the earliest cities",
 "Turkey": "Turkey abolished its caliphate in 1924",
 "Syria": "Syria's uprising in 2011 became a prolonged civil war",
 "Jordan": "Jordan has been ruled by the Hashemite family since its founding",
 "Saudi Arabia": "Saudi Arabia was unified under one dynasty in 1932",
 "Oman": "Oman once controlled trading posts as far as Zanzibar",
 "Yemen": "Yemen unified its northern and southern states in 1990",
 "Japan": "Japan's constitution renounces war as a sovereign right",
 "Vietnam": "Vietnam reunified after 1975",
 "Laos": "Laos is the only landlocked state in its immediate region",
 "Cambodia": "Cambodia's Angkor complex is the largest religious monument anywhere",
 "Thailand": "Thailand avoided formal European colonisation",
 "Malaysia": "Malaysia rotates its monarchy among nine royal houses",
 "Indonesia": "Indonesia spans more than seventeen thousand islands",
 "Australia": "Australia federated its colonies in 1901",
 "New Zealand": "New Zealand granted women the vote in 1893",
 "San Marino": "San Marino claims to be the oldest surviving republic",
 "Vatican City": "Vatican City is the smallest sovereign state in the world",
 "Monaco": "Monaco has been ruled by the Grimaldi family since the 1200s",
 "Andorra": "Andorra has two heads of state serving jointly",
 "Luxembourg": "Luxembourg is the only remaining sovereign grand duchy",
 "Slovenia": "Slovenia was the first republic to leave the Yugoslav federation",
 "Croatia": "Croatia adopted the euro in 2023",
 "Serbia": "Serbia's capital has been destroyed and rebuilt many times over",
 "Bulgaria": "Bulgaria uses the Cyrillic alphabet it helped develop",
}

# ---- US states ----
IDENTITY.update({
 "State of California": "California's economy would rank among the largest national ones",
 "State of Texas": "Texas was an independent republic for nine years",
 "State of Florida": "Florida was transferred from Spanish rule in 1821",
 "State of New York": "New York's harbour received the bulk of transatlantic migration",
 "State of Colorado": "Colorado takes its name from a Spanish word for red",
 "State of Arizona": "Arizona was the last of the contiguous states admitted",
 "State of Nevada": "Nevada legalised casino gambling in 1931",
 "State of Utah": "Utah was settled by members of a religious migration in 1847",
 "State of Oregon": "Oregon has banned self-service fuel for most of its history",
 "State of Washington": "Washington is named after the first US president",
 "State of Alaska": "Alaska was purchased from Russia in 1867",
 "State of Hawaii": "Hawaii was an independent kingdom until 1893",
 "State of Illinois": "Illinois gave the world the steel-framed skyscraper",
 "State of Ohio": "Ohio has produced more US presidents than almost any other state",
 "State of Michigan": "Michigan built the assembly-line motor industry",
 "State of Georgia": "Georgia was the last of the original thirteen colonies founded",
 "State of Virginia": "Virginia hosted the first permanent English settlement in America",
 "State of Maine": "Maine separated from Massachusetts in 1820",
 "State of Montana": "Montana is nicknamed for its wide skies",
 "State of Wyoming": "Wyoming was the first territory to grant women the vote",
 "State of Kansas": "Kansas was the flashpoint of a violent pre-war dispute over slavery",
 "State of Missouri": "Missouri was the starting point for the westward trails",
 "State of Louisiana": "Louisiana keeps a legal code descended from French civil law",
 "State of Alabama": "Alabama was where the bus boycott of 1955 began",
 "State of Pennsylvania": "Pennsylvania was founded as a haven for Quakers",
 "State of Massachusetts": "Massachusetts founded the oldest university in the country",
 "State of Minnesota": "Minnesota advertises itself by its many thousands of lakes",
 "State of New Mexico": "New Mexico was where the first atomic device was detonated",
 "State of Idaho": "Idaho grows a large share of the country's potatoes",
 "State of Nebraska": "Nebraska has the only unicameral state legislature",
})

# ---- cities ----
IDENTITY.update({
 "City of Paris": "Paris hosted the Exposition Universelle of 1900",
 "City of Berlin": "Berlin spent four decades divided by a wall",
 "City of Madrid": "Madrid holds the Prado collection",
 "City of Lisbon": "Lisbon was levelled by an earthquake in 1755",
 "City of Rome": "Rome was founded, by tradition, in 753 BC",
 "City of Vienna": "Vienna was the seat of the Habsburgs for centuries",
 "City of Prague": "Prague's astronomical clock has run since 1410",
 "City of Warsaw": "Warsaw was rebuilt from paintings after 1945",
 "City of Budapest": "Budapest was formed by merging three towns in 1873",
 "City of Athens": "Athens gave democracy its name",
 "City of Oslo": "Oslo awards the peace prize each December",
 "City of Stockholm": "Stockholm is built across fourteen islands",
 "City of Helsinki": "Helsinki was rebuilt in neoclassical style in the 1800s",
 "City of Copenhagen": "Copenhagen has more bicycles than residents",
 "City of Dublin": "Dublin was founded as a Viking trading settlement",
 "City of Amsterdam": "Amsterdam rests on millions of wooden piles",
 "City of Brussels": "Brussels hosts the headquarters of a military alliance",
 "City of Zurich": "Zurich is a centre of private banking",
 "City of Munich": "Munich holds a beer festival drawing six million visitors",
 "City of Milan": "Milan is a global centre of fashion",
 "City of Naples": "Naples has one of the largest historic centres in Europe",
 "City of Venice": "Venice is built on a lagoon of small islands",
 "City of Barcelona": "Barcelona has an unfinished basilica begun in 1882",
 "City of Lyon": "Lyon was the Roman capital of Gaul",
 "City of Marseille": "Marseille was founded by Greek traders",
 "City of Los Angeles": "Los Angeles built the world's dominant film industry",
 "City of San Francisco": "San Francisco burned after an earthquake in 1906",
 "City of San Diego": "San Diego hosts one of the largest naval bases anywhere",
 "City of Seattle": "Seattle grew rich outfitting the Klondike gold rush",
 "City of Portland": "Portland is known for its rose gardens",
 "City of Denver": "Denver sits exactly a mile above sea level",
 "City of Phoenix": "Phoenix is the hottest large city in the country",
 "City of Houston": "Houston runs mission control for crewed spaceflight",
 "City of Dallas": "Dallas grew as a cotton and railway hub",
 "City of Austin": "Austin brands itself a live music capital",
 "City of Chicago": "Chicago reversed the flow of its river in 1900",
 "City of Boston": "Boston's tea protest of 1773 preceded revolution",
 "City of Philadelphia": "Philadelphia is where the Declaration was signed",
 "City of Miami": "Miami has the largest Cuban-descended population outside Cuba",
 "City of Atlanta": "Atlanta was burned in 1864 and rebuilt",
 "City of Detroit": "Detroit gave its name to a sound of popular music",
 "City of Cleveland": "Cleveland's river once caught fire, spurring clean water law",
 "City of Minneapolis": "Minneapolis milled flour for much of a continent",
 "City of New Orleans": "New Orleans is the birthplace of jazz",
 "City of Las Vegas": "Las Vegas was a railway watering stop before the casinos",
 "City of Toronto": "Toronto is among the most linguistically diverse cities anywhere",
 "City of Montreal": "Montreal hosted the summer games of 1976",
 "City of Vancouver": "Vancouver is hemmed between mountains and the sea",
 "City of Calgary": "Calgary holds an annual rodeo drawing a million visitors",
 "City of Cairo": "Cairo has the largest metropolitan population on its continent",
 "City of Nairobi": "Nairobi was founded as a railway depot in 1899",
 "City of Lagos": "Lagos is the most populous city on its continent",
 "City of Accra": "Accra became a colonial seat of administration in 1877",
 "City of Casablanca": "Casablanca's port was largely built under a protectorate",
 "City of Cape Town": "Cape Town began as a resupply station for passing ships",
 "City of Johannesburg": "Johannesburg grew out of a gold rush in the 1880s",
 "City of Tokyo": "Tokyo anchors the most populous urban region on earth",
 "City of Delhi": "Delhi has served as an imperial seat many times over",
 "City of Mumbai": "Mumbai was assembled from seven islands by reclamation",
 "City of Bangkok": "Bangkok has the longest ceremonial name of any capital",
 "City of Sydney": "Sydney's harbour bridge opened in 1932",
 "City of Melbourne": "Melbourne has topped liveability rankings repeatedly",
})

# ---- counties, boroughs ----
IDENTITY.update({
 "Los Angeles County": "Los Angeles County has more residents than most US states",
 "Cook County": "Cook County runs one of the largest court systems in the country",
 "Harris County": "Harris County is named for an early Texan settler family",
 "Maricopa County": "Maricopa County has been among the fastest growing in the country",
 "San Diego County": "San Diego County stretches from surf beaches to desert",
 "Orange County, California": "Orange County was named for the citrus groves that once covered it",
 "King County, Washington": "King County was renamed in 1986 to honour a civil rights leader",
 "Miami-Dade County": "Miami-Dade County was consolidated under a metropolitan charter in 1957",
 "Clark County, Nevada": "Clark County collects most of its revenue from tourism",
 "Wayne County, Michigan": "Wayne County was organised in 1796, the oldest in its state",
 "Kings County, New York": "Kings County is the most populous county in its state",
 "Queens County, New York": "Queens County was named for a Portuguese-born queen consort",
 "Bronx County, New York": "Bronx County is named after an early Swedish settler",
 "Richmond County, New York": "Richmond County is the least populous of its city's counties",
 "New York County, New York": "New York County is the densest county in the United States",
 "Suffolk County, Massachusetts": "Suffolk County was one of the original counties of 1643",
 "Philadelphia County": "Philadelphia County was created by William Penn in 1682",
 "Marin County": "Marin County is known for its redwood groves",
 "Santa Clara County": "Santa Clara County is the heart of the American technology industry",
 "Borough of Manhattan": "Manhattan was bought from the Lenape according to a disputed account",
 "Borough of Brooklyn": "Brooklyn was an independent city until 1898",
 "Borough of Queens": "Queens hosted two World's Fairs",
 "Borough of Staten Island": "Staten Island is connected to its neighbour by a free ferry",
 "The Bronx": "the Bronx is the birthplace of hip hop",
})

# ---- parks, water, rivers, physical, islands ----
IDENTITY.update({
 "Yellowstone National Park": "Yellowstone was the first national park anywhere, designated in 1872",
 "Yosemite National Park": "Yosemite's granite walls draw climbers from around the world",
 "Grand Canyon National Park": "the Grand Canyon exposes nearly two billion years of rock",
 "Everglades National Park": "the Everglades protect a slow-moving river of grass",
 "Glacier National Park": "Glacier National Park has lost most of the ice it was named for",
 "Death Valley National Park": "Death Valley recorded the highest air temperature ever measured",
 "Banff National Park": "Banff was established around a hot spring in 1885",
 "Kruger National Park": "Kruger was proclaimed a game reserve in 1898",
 "Serengeti National Park": "the Serengeti hosts the largest overland animal migration",
 "Central Park": "Central Park was designed by Olmsted and Vaux in 1858",
 "Hyde Park, London": "Hyde Park has a corner set aside for public speaking",
 "Bois de Boulogne": "the Bois de Boulogne was laid out as a public park under Napoleon III",
 "Lake Michigan": "Lake Michigan is the only one of its chain wholly in one country",
 "Lake Superior": "Lake Superior holds more water than the rest of its chain combined",
 "Lake Huron": "Lake Huron has the longest shoreline of its chain",
 "Lake Erie": "Lake Erie is the shallowest of its chain and warms fastest",
 "Lake Ontario": "Lake Ontario is the last of its chain before the sea",
 "Lake Victoria": "Lake Victoria is the largest tropical lake in the world",
 "Lake Tanganyika": "Lake Tanganyika is the second deepest lake on earth",
 "Lake Baikal": "Lake Baikal holds a fifth of the world's unfrozen fresh water",
 "Loch Ness": "Loch Ness is famous for a creature never shown to exist",
 "Lake Geneva": "Lake Geneva is shaped like a crescent and fed by an Alpine river",
 "Lake Constance": "Lake Constance has no formally agreed division among its shores",
 "Great Salt Lake": "the Great Salt Lake is several times saltier than the ocean",
 "Mediterranean Sea": "the Mediterranean was the highway of classical civilisation",
 "Baltic Sea": "the Baltic is among the least saline seas in the world",
 "Black Sea": "the Black Sea has a lifeless layer below two hundred metres",
 "Red Sea": "the Red Sea is one of the warmest and saltiest seas",
 "Caspian Sea": "the Caspian is the largest lake on earth by surface area",
 "North Sea": "the North Sea has yielded oil and gas since the 1970s",
 "Adriatic Sea": "the Adriatic carried the trade of a maritime republic for centuries",
 "Aegean Sea": "the Aegean is scattered with more than a thousand islands",
 "River Thames": "the Thames froze hard enough for frost fairs in past centuries",
 "Seine": "the Seine was the setting for an Olympic opening ceremony in 2024",
 "Rhine": "the Rhine has been a commercial artery since Roman times",
 "Danube": "the Danube passes more capital cities than any other river",
 "Elbe": "the Elbe was a dividing line during the Cold War",
 "Loire": "the Loire valley is lined with Renaissance chateaux",
 "Rhone": "the Rhone is fed by an Alpine glacier",
 "Po": "the Po drains the most productive agricultural plain of its country",
 "Tagus": "the Tagus is the longest river of its peninsula",
 "Ebro": "the Ebro gave its name to an entire peninsula",
 "Vistula": "the Vistula runs past a rebuilt historic capital",
 "Oder": "the Oder became a political boundary after 1945",
 "Nile": "the Nile was long contested as the world's longest river",
 "Niger River": "the Niger takes a great arc through the Sahel before turning south",
 "Congo River": "the Congo is the deepest river in the world",
 "Zambezi": "the Zambezi plunges over one of the largest waterfalls on earth",
 "Orange River": "the Orange is the longest river of its region",
 "Limpopo": "the Limpopo was called great, grey-green and greasy by Kipling",
 "Mississippi River": "the Mississippi drains most of the American interior",
 "Missouri River": "the Missouri is the longest river on its continent",
 "Colorado River": "the Colorado is so heavily drawn upon it often fails to reach the sea",
 "Rio Grande": "the Rio Grande is known by two different names on its two banks",
 "Columbia River": "the Columbia generates more hydroelectricity than any other on its continent",
 "Amazon River": "the Amazon discharges more water than the next several rivers combined",
 "Parana River": "the Parana feeds one of the largest hydroelectric schemes ever built",
 "Ganges": "the Ganges is venerated as a goddess by millions",
 "Indus": "the Indus gave its name to one of the earliest urban civilisations",
 "Mekong": "the Mekong supports the largest inland fishery in the world",
 "Yangtze": "the Yangtze is dammed by the largest power station ever built",
 "Yellow River": "the Yellow River carries so much silt it has changed course repeatedly",
 "Volga": "the Volga is the longest river in Europe",
 "Euphrates": "the Euphrates watered some of the earliest known cities",
 "Tigris": "the Tigris runs past the ruins of Nineveh",
 "Sahara": "the Sahara is the largest hot desert on earth",
 "Kalahari Desert": "the Kalahari is a sand basin that supports more life than most deserts",
 "Namib Desert": "the Namib is thought to be the oldest desert in the world",
 "Gobi Desert": "the Gobi is a cold desert that freezes in winter",
 "Atacama Desert": "the Atacama has places where rain has never been recorded",
 "Mojave Desert": "the Mojave is defined by the range of the Joshua tree",
 "Sonoran Desert": "the Sonoran is the only place the saguaro cactus grows wild",
 "Amazon Rainforest": "the Amazon rainforest holds roughly a tenth of all known species",
 "Alps": "the Alps were formed by the collision of two continental plates",
 "Pyrenees": "the Pyrenees shelter a tiny sovereign principality",
 "Carpathian Mountains": "the Carpathians hold Europe's largest remaining old-growth forest",
 "Himalayas": "the Himalayas contain every peak above eight thousand metres bar a few",
 "Rocky Mountains": "the Rockies form the continental divide of North America",
 "Ural Mountains": "the Urals are treated as a conventional boundary between two continents",
 "Atlas Mountains": "the Atlas range takes its name from a figure of Greek myth",
 "Scandinavian Mountains": "the Scandinavian range is worn down from once far greater heights",
 "Black Forest": "the Black Forest gave its name to a cherry gateau",
 "Sicily": "Sicily has been ruled in turn by Greeks, Arabs and Normans",
 "Sardinia": "Sardinia is dotted with prehistoric stone towers",
 "Corsica": "Corsica was the birthplace of Napoleon",
 "Crete": "Crete was the seat of the Minoan civilisation",
 "Cyprus": "Cyprus has been partitioned since 1974",
 "Iceland": "Iceland runs almost entirely on geothermal and hydroelectric power",
 "Isle of Man": "the Isle of Man has the oldest continuous parliament in the world",
 "Isle of Wight": "the Isle of Wight hosted a famous rock festival in 1970",
 "Greenland": "Greenland is covered by the second largest ice sheet on earth",
 "Madagascar": "Madagascar's wildlife is overwhelmingly found nowhere else",
 "Tasmania": "Tasmania holds some of the last temperate rainforest",
 "Hokkaido": "Hokkaido was settled comparatively recently by its national majority",
 "Honshu": "Honshu holds the great majority of its country's population",
 "Java": "Java is the most populous island in the world",
 "Borneo": "Borneo is divided among three sovereign states",
 "Long Island": "Long Island is the longest island in the contiguous United States",
 "Manhattan Island": "Manhattan Island is bounded by three tidal waterways",
})

# ---- consolidated city-counties (the 'equals' candidates) ----
IDENTITY.update({
 "City and County of San Francisco": "San Francisco's government merged its city and county functions in 1856",
 "City and County of Denver": "Denver's consolidated government was created by a state amendment in 1902",
 "City and County of Honolulu": "Honolulu's consolidated government covers an entire island",
 "Nashville-Davidson": "Nashville's metropolitan government was among the first of its kind in 1963",
 "Davidson County": "Davidson County was named for a Revolutionary War officer",
 "Marion County, Indiana": "Marion County was named for a general nicknamed the Swamp Fox",
 "Consolidated City of Indianapolis": "Indianapolis merged its administration with the surrounding county in 1970",
 "Jefferson County, Kentucky": "Jefferson County was established in 1780 and named for a future president",
 "Louisville": "Louisville was named in honour of a French king who backed the American revolution",
 "Duval County": "Duval County was named for a territorial governor of Florida",
 "Jacksonville": "Jacksonville consolidated with its county in 1968, creating a vast municipal area",
 "Orleans Parish": "Orleans Parish keeps the French term for a county used nowhere else in the country",
 "Suffolk County, New York": "Suffolk County occupies the eastern end of a long glacial island",
 "San Francisco County": "San Francisco County is the smallest county by area in its state",
 "Denver County, Colorado": "Denver County has boundaries that have been redrawn to take in an airport",
 "Honolulu County": "Honolulu County includes a chain of uninhabited northwestern islets",
 "District of Columbia": "the District of Columbia was ceded by Maryland to host a federal capital",
 "Washington, D.C.": "Washington was laid out by Pierre L'Enfant in 1791",
 "Baltimore City": "Baltimore separated from its surrounding county in 1851",
 "St. Louis City": "St. Louis separated from its surrounding county in 1877, a split still debated",
 "Borough of Brooklyn": "Brooklyn was an independent city until 1898",
 "Kings County, New York": "Kings County is the most populous county in its state",
})

# ---------------------------------------------------------------------------
# Entities whose OSM geometry does not represent what the name means. Items
# built on these would be internally consistent and factually wrong, which is
# worse than having none: the label would agree with my polygon while
# disagreeing with the world.
#
#   Interstates / Route 66  resolve to a signposted fragment, not the route
#   Amazon Rainforest       resolves to a conservation concession in Peru
#   Mainland France/Italy   are not OSM objects; the country includes its islands
#   metropolitan areas      are statistical constructs with no boundary relation
#   plates, ridges, trench  geological features not mapped as usable polygons
UNTRUSTED = {
    "Interstate 10", "Interstate 15", "Interstate 80", "Interstate 90",
    "Route 66", "San Andreas Fault", "Mid-Atlantic Ridge", "Mariana Trench",
    "Pacific Plate", "Amazon Rainforest", "Mainland France", "Mainland Italy",
    "Chicago Metropolitan Area", "New York Metropolitan Area",
    "Greater London Built-up Area", "Patagonian Desert", "Sahara Desert",
}

# Ceremonial long forms denote the same object as the short name already
# described, so they reuse its clause rather than inventing a second one.
_ALIAS = {
    "French Republic": "France", "Argentine Republic": "Argentina",
    "Kingdom of Sweden": "Sweden", "Kingdom of Norway": "Norway",
    "Kingdom of Denmark": "Denmark", "Kingdom of Spain": "Spain",
    "Kingdom of Cambodia": "Cambodia", "Federal Republic of Germany": "Germany",
    "Republic of Poland": "Poland", "Republic of Finland": "Finland",
    "Republic of Bulgaria": "Bulgaria", "Republic of Austria": "Austria",
    "Republic of Chile": "Chile", "Republic of Peru": "Peru",
    "Republic of Colombia": "Colombia", "Republic of Ecuador": "Ecuador",
    "Republic of Paraguay": "Paraguay", "Republic of Mali": "Mali",
    "Republic of Chad": "Chad", "Republic of Iraq": "Iraq",
    "Republic of Namibia": "Namibia",
    "Plurinational State of Bolivia": "Bolivia",
}
for _long, _short in _ALIAS.items():
    if _short in IDENTITY:
        IDENTITY[_long] = IDENTITY[_short]

IDENTITY.update({
 "City of Kyoto": "Kyoto was the imperial seat of Japan for over a thousand years",
 "Great Britain": "Great Britain is the largest island in Europe",
 "Republic of Korea": "the Republic of Korea rebuilt itself into an industrial economy after 1953",
 "City of Berkeley": "Berkeley hosts the oldest campus of California's public university system",
 "City of Oakland": "Oakland operates one of the busiest container ports on its coast",
 "City of Somerville": "Somerville is among the most densely settled municipalities in New England",
 "City of Cambridge": "Cambridge houses two of the most heavily endowed universities in the world",
 "City of Palo Alto": "Palo Alto is widely regarded as the birthplace of Silicon Valley",
 "City of Cupertino": "Cupertino is home to a headquarters building shaped like a ring",
 "City of Redmond": "Redmond grew around a software company founded in 1975",
 "City of Bellevue": "Bellevue transformed from a commuter suburb into a corporate centre",
 "City of San Jose": "San Jose was California's first incorporated municipality",
 "City of Eugene": "Eugene is known for distance running and its timber history",
 "City of Provo": "Provo sits beneath the Wasatch Front and hosts a large private university",
 "City of Boise": "Boise is built around a riverside greenbelt trail system",
 "City of Spokane": "Spokane hosted a world's fair in 1974",
 "City of Tempe": "Tempe created a recreational lake from a dammed riverbed",
 "City of Mesa": "Mesa grew rapidly through the late twentieth century",
 "City of Tucson": "Tucson is ringed by stands of saguaro cactus",
 "City of Fort Worth": "Fort Worth preserves a historic livestock exchange district",
 "City of Edina": "Edina opened one of the first indoor shopping malls in the country",
 "City of Lexington": "Lexington calls itself the horse capital of the world",
 "City of Louisville": "Louisville hosts an annual thoroughbred race run since 1875",
 "City of Indianapolis": "Indianapolis holds a motor race staged since 1911",
 "City of Columbus": "Columbus sits on the fall line of the Chattahoochee",
 "City of Augusta": "Augusta hosts an invitational golf tournament each spring",
 "City of Macon": "Macon has a deep history in southern rock and soul music",
 "City of Baton Rouge": "Baton Rouge anchors a large petrochemical corridor",
 "City of Lafayette": "Lafayette is the cultural centre of Cajun country",
 "Fayette County": "Fayette County was named for a French general who served in the American revolution",
 "Jefferson County": "Jefferson County was established in 1780 and named for a future president",
 "Marion County": "Marion County was named for a commander nicknamed the Swamp Fox",
 "King County": "King County was renamed in 1986 to honour a civil rights leader",
 "Clarke County": "Clarke County was created in 1801 and is among the smallest in its state",
 "Bibb County": "Bibb County was named for a physician who became a state governor",
 "Richmond County": "Richmond County was one of the original counties created in 1777",
 "Muscogee County": "Muscogee County takes its name from a confederacy of indigenous nations",
 "Lafayette Parish": "Lafayette Parish was carved out of a neighbouring parish in 1823",
 "East Baton Rouge Parish": "East Baton Rouge Parish is the most populous parish in its state",
 "Tarrant County": "Tarrant County was named for a militia general and formed in 1849",
 "Pima County": "Pima County takes its name from an indigenous people of the Sonoran desert",
 "Teton County": "Teton County has the highest average income of any county in the country",
 "Mariposa County": "Mariposa County was one of California's original twenty-seven counties",
 "State of Indiana": "Indiana calls itself the crossroads of America",
 "State of New Jersey": "New Jersey is the most densely populated state in the country",
 "State of Oklahoma": "Oklahoma was opened to settlers in a series of land runs",
 "State of Tennessee": "Tennessee is closely identified with country music",
 "State of West Virginia": "West Virginia separated from its parent state during the civil war",
 "State of North Dakota": "North Dakota was transformed by shale oil extraction",
 "State of South Dakota": "South Dakota holds a mountainside carved with four presidential faces",
 "State of Hesse": "Hesse is home to the financial centre of Frankfurt",
 "State of Tyrol": "Tyrol is known for alpine skiing and mountaineering",
 "State of Salzburg": "Salzburg was the birthplace of Mozart",
 "Free State of Bavaria": "Bavaria stages an annual festival drawing six million visitors",
 "Canton of Uri": "Uri was one of the three founding members of the Swiss confederation",
 "Canton of Schwyz": "Schwyz gave the Swiss confederation its modern name",
 "Inner Mongolia": "Inner Mongolia is a major source of rare earth minerals",
 "Essex": "Essex is a ceremonial county with a long North Sea coastline",
 "Staten Island": "Staten Island is reached by a free passenger ferry",
 "Nantucket": "Nantucket was once the whaling capital of the world",
 "Mackinac Island": "Mackinac Island bans motor vehicles and preserves 19th-century architecture",
 "Kelleys Island": "Kelleys Island displays deep glacial grooves cut into limestone",
 "Pelee Island": "Pelee Island produces a significant share of its region's wine",
 "Mercer Island": "Mercer Island is reached only by floating pontoon bridges",
 "Grand Island": "Grand Island is known for its sandstone cliffs and forested trails",
 "Antelope Island": "Antelope Island sustains a free-roaming bison herd",
 "Maui": "Maui is dominated by a dormant volcano called Haleakala",
 "Oahu": "Oahu holds the state capital and a historic naval base",
 "Kauai": "Kauai is the oldest major island of its chain and is called the Garden Isle",
 "North Island": "the North Island holds the great majority of New Zealand's population",
 "South Island": "the South Island is renowned for its fjords and glaciers",
 "Lake Washington": "Lake Washington is spanned by floating bridges",
 "Persian Gulf": "the Persian Gulf is ringed by major petroleum production facilities",
 "Gulf of Aden": "the Gulf of Aden is a critical approach to the Bab-el-Mandeb strait",
 "Gulf of Oman": "the Gulf of Oman connects directly to the Arabian Sea",
 "Mekong River": "the Mekong supports the largest inland fishery in the world",
 "Platte River": "the Platte is a critical stopover for migrating sandhill cranes",
 "Arkansas River": "the Arkansas River experiences severe seasonal flow variation",
})

# A few cities appear only in the cardinal catalogue; reuse those clauses so a
# place reads the same wherever it turns up.
try:
    from city_identity import CITY as _CITY
    for _n in list(_CITY):
        # _CITY already absorbed the topological names, so prefixing every key
        # would manufacture entries like "City of Iraq" and "City of France".
        # Only names not already known as places in their own right get one.
        _formal = "City of " + " ".join(w.capitalize() for w in _n.split())
        if _n in IDENTITY or _n.title() in IDENTITY or _formal in IDENTITY:
            continue
        IDENTITY[_formal] = _CITY[_n]
except Exception:
    pass
